$axure.loadCurrentPage({
  "url":"客服.html",
  "generationDate":new Date(1479704710640.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"95a7dfd3635c494d9e187f842d9f6928",
    "type":"Axure:Page",
    "name":"客服",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"56714a2bdc0e4afe998e7c93a2105277",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a086e7cb87c144058818b9a3550c238f"},
{
          "id":"f2214e23e8334cc081d1dcde346f65e5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":135},
            "size":{
              "width":32,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"68835587dad74a17b15362230fbc1cb0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":106},
            "size":{
              "width":374,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc02cff467414b1a981305445b256e70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":106},
                "size":{
                  "width":374,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服--我的预约/u4.png"}},
{
          "id":"f57b1cbbc4f4445983c3781694c9ea08",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":675},
            "size":{
              "width":40,
              "height":45}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 你",
                      "objectsToFades":[{
                          "objectPath":["847a37c2dda2449eb3cea5aaebfbe92d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"b2afc14fa19b4749b0b90dde7e2e93b6",
          "label":"你好消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":27,
              "y":310},
            "size":{
              "width":373,
              "height":140},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0f1c527a5f4424bf821b1ce1cbe820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":27,
                  "y":310},
                "size":{
                  "width":373,
                  "height":140},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服--我的预约/你好消息_u7.png"}},
{
          "id":"847a37c2dda2449eb3cea5aaebfbe92d",
          "label":"你",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":50,
              "y":502},
            "size":{
              "width":14,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ffe876efae74544b3d02e87fa74b4cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":50,
                  "y":502},
                "size":{
                  "width":14,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77f5e87a9a7746f792bd7fda35d25417",
          "label":"好",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":66,
              "y":503},
            "size":{
              "width":14,
              "height":16},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3daa60a96bc4187a01d3a31d3657176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":66,
                  "y":503},
                "size":{
                  "width":14,
                  "height":16},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e71a053ed4a43a4a3badf2cc4894b79",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":620},
            "size":{
              "width":35,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 好",
                      "objectsToFades":[{
                          "objectPath":["77f5e87a9a7746f792bd7fda35d25417"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"60e9ee47551c443a8c83b43ec51a5e3b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":496},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 好,<br>你",
                      "objectsToFades":[{
                          "objectPath":["77f5e87a9a7746f792bd7fda35d25417"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["847a37c2dda2449eb3cea5aaebfbe92d"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 你好消息",
                      "objectsToFades":[{
                          "objectPath":["b2afc14fa19b4749b0b90dde7e2e93b6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"bb406cc9a88347c286b1ec9841c36b8c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":128},
            "size":{
              "width":32,
              "height":42}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "a086e7cb87c144058818b9a3550c238f":{
      "packageId":"a086e7cb87c144058818b9a3550c238f",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"623c214f22b644b990c3bc1c0a100f4d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":430,
                "height":880}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7feffeea2daa4300973110505dfb8fb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":430,
                    "height":880}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/app/u1.jpg"}}]}}},
  "objectPaths":{
    "56714a2bdc0e4afe998e7c93a2105277":{
      "scriptId":"u0",
      "623c214f22b644b990c3bc1c0a100f4d":{
        "scriptId":"u1"},
      "7feffeea2daa4300973110505dfb8fb0":{
        "scriptId":"u2"}},
    "f2214e23e8334cc081d1dcde346f65e5":{
      "scriptId":"u3"},
    "68835587dad74a17b15362230fbc1cb0":{
      "scriptId":"u4"},
    "dc02cff467414b1a981305445b256e70":{
      "scriptId":"u5"},
    "f57b1cbbc4f4445983c3781694c9ea08":{
      "scriptId":"u6"},
    "b2afc14fa19b4749b0b90dde7e2e93b6":{
      "scriptId":"u7"},
    "7a0f1c527a5f4424bf821b1ce1cbe820":{
      "scriptId":"u8"},
    "847a37c2dda2449eb3cea5aaebfbe92d":{
      "scriptId":"u9"},
    "6ffe876efae74544b3d02e87fa74b4cb":{
      "scriptId":"u10"},
    "77f5e87a9a7746f792bd7fda35d25417":{
      "scriptId":"u11"},
    "d3daa60a96bc4187a01d3a31d3657176":{
      "scriptId":"u12"},
    "1e71a053ed4a43a4a3badf2cc4894b79":{
      "scriptId":"u13"},
    "60e9ee47551c443a8c83b43ec51a5e3b":{
      "scriptId":"u14"},
    "bb406cc9a88347c286b1ec9841c36b8c":{
      "scriptId":"u15"}}});