$axure.loadCurrentPage({
  "url":"套餐方案.html",
  "generationDate":new Date(1488665387726.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"34650a350b7140b7b047cf8d6ae612c6",
    "type":"Axure:Page",
    "name":"套餐方案",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1a275224bd0044148ae22c52848ac48a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86534d04f4c54a478219ea4f0e3f506b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u0.jpg"}},
{
          "id":"e62d265d86fa4eff9dc2ab71262c132f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd7ca7c836af4e13b4a59a2592298aae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u2.png"}},
{
          "id":"f8cca37cc79143198462b144890a13ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c95fe16e5d4426b63955fcab16173e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u4.png"}},
{
          "id":"dd7b25bcaf29483e9c6644a756b79a26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":54},
            "size":{
              "width":123,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eedd4752c17401994752d6af4cecafb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":54},
                "size":{
                  "width":123,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u6.png"}},
{
          "id":"2287d107d62340419b56a6a0648b37ef",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":47},
            "size":{
              "width":66,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8f815a2d46884870995e59c52b775c92",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":182},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 素材库",
                      "target":{
                        "targetType":"page",
                        "url":"素材库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"33f68dba00a7455a99e8f2c3002101eb",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":284},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收藏",
                      "target":{
                        "targetType":"page",
                        "url":"收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"102f853d52ef4df9a04349e7271f5fe4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":234},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐配置",
                      "target":{
                        "targetType":"page",
                        "url":"套餐配置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a3b181f8812a412fa92d1146ca5a26f7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8d4b3e0c10e14258bcb652fae7e4eb93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":242.5},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb1d7309f544045ae80c622648b84e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":242.5},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐配置",
                      "target":{
                        "targetType":"page",
                        "url":"套餐配置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"7887eb7bd48b4e6f82981a352ede9dbd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c305b93130374d05b269156a4bd28547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"47453e1995bb4f8489a9e0372b74e63c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1470,
              "y":59},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c703a9b41f4da69e4af45d5cf0161f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1470,
                  "y":59},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"0a46f4307a354780afb515d49d96dbdc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":186},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab31b005931c41f4957aa06e21d6d54d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":186},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 素材库",
                      "target":{
                        "targetType":"page",
                        "url":"素材库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"1c7405ad60864eb88d9a145bc7cde2c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":286},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a426c4d84c604eff945914ffeaa2c980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":286},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收藏",
                      "target":{
                        "targetType":"page",
                        "url":"收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"5f3f5b6122ca48c6a4d8a0981cacbfa4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":802}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9802792ffa854e8ba27f24b0222cb391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":802}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u23.png"}},
{
          "id":"83fc4609c13a4eb884bfd8d11ae85408",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cc8351499bfd46e1807a42fce160f44b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdb5897ff6314a29a1a3c33a421fac98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":305,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"f118d0059e104fefbf88b9650c17cbb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":148.5,
              "y":42},
            "size":{
              "width":360,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db83e31a6d124bb6b5c37653ba15233d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148.5,
                  "y":42},
                "size":{
                  "width":360,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u28.png"}},
{
          "id":"82be54a7a9754c849b8bd3c4c23c6640",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":750},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c787b6a1452640f2a9928b9924cbfdb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":820},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"937f49f74f9a4da4badd51b1de1922e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":820},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"9e81ca99c1d64358bfd0ce61b9ee649d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4B5161},
            "location":{
              "x":2,
              "y":136},
            "size":{
              "width":46,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"030e1dc41f3b4d18a853efc2fb22e555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4B5161},
                "location":{
                  "x":2,
                  "y":136},
                "size":{
                  "width":46,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u33.png"}},
{
          "id":"624922e502d8454587a7d51ee35ccb18",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":196.5},
            "size":{
              "width":37,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc0ac09856e488dbbbe81bd01bc501b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":196.5},
                "size":{
                  "width":37,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a524835e22c74a549ab9517eaf47a125",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":147},
            "size":{
              "width":37,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f520eb7c680f420c9fb258a320fa0a57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":147},
                "size":{
                  "width":37,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec0f5dd601c546fabc6a7b9aa30ba427",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb8cdd1944864dcfa43fc31df561bb4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u39.png"}},
{
          "id":"3dab6160e2b44dfda6572b720bdcb290",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f2a85604d5d4ef69b31a432ecbfde55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u41.png"}},
{
          "id":"a9ea2e01689c4aa4960b26ce74cf7e7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1011,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5168ba5c66164725af0dd849549b2894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1011,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u43.png"}},
{
          "id":"9a5b5170be8c427494298ecc06480354",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1240,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c770f2c2d17f49b3a82ef1cb4cab944a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1240,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u45.png"}},
{
          "id":"650fbadd44ca4ee598bced53f0145bd4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1651fee46554fc3befc67913352f63d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u47.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1a275224bd0044148ae22c52848ac48a":{
      "scriptId":"u0"},
    "86534d04f4c54a478219ea4f0e3f506b":{
      "scriptId":"u1"},
    "e62d265d86fa4eff9dc2ab71262c132f":{
      "scriptId":"u2"},
    "fd7ca7c836af4e13b4a59a2592298aae":{
      "scriptId":"u3"},
    "f8cca37cc79143198462b144890a13ae":{
      "scriptId":"u4"},
    "96c95fe16e5d4426b63955fcab16173e":{
      "scriptId":"u5"},
    "dd7b25bcaf29483e9c6644a756b79a26":{
      "scriptId":"u6"},
    "9eedd4752c17401994752d6af4cecafb":{
      "scriptId":"u7"},
    "2287d107d62340419b56a6a0648b37ef":{
      "scriptId":"u8"},
    "8f815a2d46884870995e59c52b775c92":{
      "scriptId":"u9"},
    "33f68dba00a7455a99e8f2c3002101eb":{
      "scriptId":"u10"},
    "102f853d52ef4df9a04349e7271f5fe4":{
      "scriptId":"u11"},
    "a3b181f8812a412fa92d1146ca5a26f7":{
      "scriptId":"u12"},
    "8d4b3e0c10e14258bcb652fae7e4eb93":{
      "scriptId":"u13"},
    "cbb1d7309f544045ae80c622648b84e5":{
      "scriptId":"u14"},
    "7887eb7bd48b4e6f82981a352ede9dbd":{
      "scriptId":"u15"},
    "c305b93130374d05b269156a4bd28547":{
      "scriptId":"u16"},
    "47453e1995bb4f8489a9e0372b74e63c":{
      "scriptId":"u17"},
    "d1c703a9b41f4da69e4af45d5cf0161f":{
      "scriptId":"u18"},
    "0a46f4307a354780afb515d49d96dbdc":{
      "scriptId":"u19"},
    "ab31b005931c41f4957aa06e21d6d54d":{
      "scriptId":"u20"},
    "1c7405ad60864eb88d9a145bc7cde2c5":{
      "scriptId":"u21"},
    "a426c4d84c604eff945914ffeaa2c980":{
      "scriptId":"u22"},
    "5f3f5b6122ca48c6a4d8a0981cacbfa4":{
      "scriptId":"u23"},
    "9802792ffa854e8ba27f24b0222cb391":{
      "scriptId":"u24"},
    "83fc4609c13a4eb884bfd8d11ae85408":{
      "scriptId":"u25"},
    "cc8351499bfd46e1807a42fce160f44b":{
      "scriptId":"u26"},
    "fdb5897ff6314a29a1a3c33a421fac98":{
      "scriptId":"u27"},
    "f118d0059e104fefbf88b9650c17cbb2":{
      "scriptId":"u28"},
    "db83e31a6d124bb6b5c37653ba15233d":{
      "scriptId":"u29"},
    "82be54a7a9754c849b8bd3c4c23c6640":{
      "scriptId":"u30"},
    "c787b6a1452640f2a9928b9924cbfdb7":{
      "scriptId":"u31"},
    "937f49f74f9a4da4badd51b1de1922e3":{
      "scriptId":"u32"},
    "9e81ca99c1d64358bfd0ce61b9ee649d":{
      "scriptId":"u33"},
    "030e1dc41f3b4d18a853efc2fb22e555":{
      "scriptId":"u34"},
    "624922e502d8454587a7d51ee35ccb18":{
      "scriptId":"u35"},
    "4dc0ac09856e488dbbbe81bd01bc501b":{
      "scriptId":"u36"},
    "a524835e22c74a549ab9517eaf47a125":{
      "scriptId":"u37"},
    "f520eb7c680f420c9fb258a320fa0a57":{
      "scriptId":"u38"},
    "ec0f5dd601c546fabc6a7b9aa30ba427":{
      "scriptId":"u39"},
    "cb8cdd1944864dcfa43fc31df561bb4b":{
      "scriptId":"u40"},
    "3dab6160e2b44dfda6572b720bdcb290":{
      "scriptId":"u41"},
    "2f2a85604d5d4ef69b31a432ecbfde55":{
      "scriptId":"u42"},
    "a9ea2e01689c4aa4960b26ce74cf7e7a":{
      "scriptId":"u43"},
    "5168ba5c66164725af0dd849549b2894":{
      "scriptId":"u44"},
    "9a5b5170be8c427494298ecc06480354":{
      "scriptId":"u45"},
    "c770f2c2d17f49b3a82ef1cb4cab944a":{
      "scriptId":"u46"},
    "650fbadd44ca4ee598bced53f0145bd4":{
      "scriptId":"u47"},
    "b1651fee46554fc3befc67913352f63d":{
      "scriptId":"u48"}}});