$axure.loadCurrentPage({
  "url":"详情页_1.html",
  "generationDate":new Date(1479704708860.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"636cd5d3cee4496d8d9c1f93d862dc64",
    "type":"Axure:Page",
    "name":"详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"77e8d82f93d04448b21245e33189cc39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec066fe0d2604d268880e0610d9a178c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"8d7e534a67874721bc1decabb340e583",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":27.5,
              "y":107.5},
            "size":{
              "width":375,
              "height":665}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 内容2 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["2918352668b54b6eb09b8b7340c9d921"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If area of 内容2 未接触 area of 固定点)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2918352668b54b6eb09b8b7340c9d921"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["6d5436d8a70344fb8a5ea1b3adf2ef0d"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 内容2 到 (0,0) 线性 200ms",
                      "objectsToMoves":[{
                          "objectPath":["2918352668b54b6eb09b8b7340c9d921"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":200}}}]}]},
{
                  "description":"用例 2<br> (Else If area of 内容2 未接触 area of 固定点)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2918352668b54b6eb09b8b7340c9d921"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["6d5436d8a70344fb8a5ea1b3adf2ef0d"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 内容2 到 (0,-30) 线性 200ms",
                      "objectsToMoves":[{
                          "objectPath":["2918352668b54b6eb09b8b7340c9d921"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-30",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":200}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"05533a3ff2ac453698bae98c728a5157",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9d13363243be4cb49e30f3962dfab290",
                  "label":"",
                  "parentDynamicPanel":"8d7e534a67874721bc1decabb340e583",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onDrag":{
                      "description":"OnDrag",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 内容2 y 轴拖动",
                              "objectsToMoves":[{
                                  "objectPath":["2918352668b54b6eb09b8b7340c9d921"],
                                  "moveInfo":{
                                    "moveType":"dragY",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
}}}]}]}]},
                    "onDragDrop":{
                      "description":"OnDragDrop",
                      "cases":[{
                          "description":"用例 1<br> (If area of 内容2 未接触 area of 固定点顶部)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"fcall",
                            "functionName":"IsNotOver",
                            "arguments":[{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["2918352668b54b6eb09b8b7340c9d921"]}]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["417fc8979c3544fa839a6aa8fe64ef5d"]}]}]},
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 内容2 到 (0,0)",
                              "objectsToMoves":[{
                                  "objectPath":["2918352668b54b6eb09b8b7340c9d921"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
}}}]}]},
{
                          "description":"用例 2<br> (Else If area of 内容2 未接触 area of 底部固定点)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"fcall",
                            "functionName":"IsNotOver",
                            "arguments":[{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["2918352668b54b6eb09b8b7340c9d921"]}]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["54bb252586f84e0cb9be875cd87a09f7"]}]}]},
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 内容2 到 (0,-850)",
                              "objectsToMoves":[{
                                  "objectPath":["2918352668b54b6eb09b8b7340c9d921"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-850",
                                      "stos":[]},
                                    "options":{
}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"e047d04a1a76430caca9c911e52aad8c",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"2918352668b54b6eb09b8b7340c9d921",
                          "label":"内容2",
                          "parentDynamicPanel":"9d13363243be4cb49e30f3962dfab290",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":377,
                              "height":1511}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"776f0e1c72db492baea64c244e0c9683",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"9d13363243be4cb49e30f3962dfab290",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":377,
                                  "height":1511}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/详情页_1/内容2_u4.jpg"}}]}]}]}]},
{
          "id":"6d5436d8a70344fb8a5ea1b3adf2ef0d",
          "label":"固定点",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":116,
              "y":88},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":116,
          "fixedVertical":"top",
          "fixedMarginVertical":88,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"91ae2aed9510423d912fdfb1f5e693be",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"417fc8979c3544fa839a6aa8fe64ef5d",
                  "label":"固定点顶部",
                  "parentDynamicPanel":"6d5436d8a70344fb8a5ea1b3adf2ef0d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b05d35b180a4e3cbb0d309a6c550c8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d5436d8a70344fb8a5ea1b3adf2ef0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/详情页/u10.png"}}]}]},
{
          "id":"72602b9b97fb492e8d459263b96ed4a7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":130},
            "size":{
              "width":42,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 预约设计师",
                      "target":{
                        "targetType":"page",
                        "url":"预约设计师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"54bb252586f84e0cb9be875cd87a09f7",
          "label":"底部固定点",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":773},
            "size":{
              "width":375,
              "height":17}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "77e8d82f93d04448b21245e33189cc39":{
      "scriptId":"u0"},
    "ec066fe0d2604d268880e0610d9a178c":{
      "scriptId":"u1"},
    "8d7e534a67874721bc1decabb340e583":{
      "scriptId":"u2"},
    "9d13363243be4cb49e30f3962dfab290":{
      "scriptId":"u3"},
    "2918352668b54b6eb09b8b7340c9d921":{
      "scriptId":"u4"},
    "776f0e1c72db492baea64c244e0c9683":{
      "scriptId":"u5"},
    "6d5436d8a70344fb8a5ea1b3adf2ef0d":{
      "scriptId":"u6"},
    "417fc8979c3544fa839a6aa8fe64ef5d":{
      "scriptId":"u7"},
    "5b05d35b180a4e3cbb0d309a6c550c8f":{
      "scriptId":"u8"},
    "72602b9b97fb492e8d459263b96ed4a7":{
      "scriptId":"u9"},
    "54bb252586f84e0cb9be875cd87a09f7":{
      "scriptId":"u10"}}});