$axure.loadCurrentPage({
  "url":"收藏.html",
  "generationDate":new Date(1488665387971.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c745d855c23244959612594110ec04dd",
    "type":"Axure:Page",
    "name":"收藏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"26d4539b226046d0a752f3718c53e2b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39969ff7aefb4fdd9ddd689561a4844c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏/u0.png"}},
{
          "id":"dcbd2d26df6944eda88f7c7bed928a04",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-25,
              "y":0},
            "size":{
              "width":1630,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba799350ecf142c7a8034b3b3e7756ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-25,
                  "y":0},
                "size":{
                  "width":1630,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏/u2.png"}},
{
          "id":"718fd469d85f43d38c1288a389d33dac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":5,
              "y":134},
            "size":{
              "width":341,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc165b97d2fe4f14a68cd10aa99e7126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":5,
                  "y":134},
                "size":{
                  "width":341,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收藏/u4.png"}},
{
          "id":"e91446421ba74b9baa7d176dc2524ba0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48424bd43f64f4897f5d6c578737d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u4.png"}},
{
          "id":"e5ab48fabbed4fe2989dd334b1705e6f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":12,
              "y":145},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"b439bb778844477b88b921433af745d2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":122,
              "y":145},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"4bcc42ae984d4feba51990f35a85ae32",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":134},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐方案",
                      "target":{
                        "targetType":"page",
                        "url":"套餐方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f9dc86103c894bb8879a494f32a1282e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":184},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 素材库",
                      "target":{
                        "targetType":"page",
                        "url":"素材库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3b60677a6ebb48cdaa8e9edbaca47584",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a5124196d61742fab02fc0671bb6c8d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":136},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80ea82a7032a441c901a5a94ca3c7511",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":136},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"018955ef88bb456293a8f8dcf8ca86a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":801}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbf27ab5a44d497fb374751f3a322d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":801}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐配置/u12.png"}},
{
          "id":"6a8f6d861a1b46cda047989acbf043b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"071b1ef058aa488c903682dd5830dd72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"615ff4fcd3914953accbca93c4d780f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":186.666656494141},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7213ea3eb1f041348ed8afe98f28f146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":186.666656494141},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 素材库",
                      "target":{
                        "targetType":"page",
                        "url":"素材库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"c323b425a24844c997d756dfbb7ac29d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":136},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5205824ba1cd4630ae3a29d38e77a5b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":136},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐方案",
                      "target":{
                        "targetType":"page",
                        "url":"套餐方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"5fcbe4f1b7c04c0baf0845ad5fe0182d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":54},
            "size":{
              "width":123,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3723752eb7d4e499d17a9e3485b5ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":54},
                "size":{
                  "width":123,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u6.png"}},
{
          "id":"b9fa61c809d34e24b358c750d483497a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":802}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79d6f14239e946d7ba94348aca83c50c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":802}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u23.png"}},
{
          "id":"13c70435a6b440c4a3e1ca98e54046af",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":47},
            "size":{
              "width":66,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f9a4616d4f8f4c85b068d5815f0ec3db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1470,
              "y":59},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f43402ea02464d48b5bc31caf7ba347a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1470,
                  "y":59},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"1ad582c51de849ff8e2a5cd5997c2f83",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":802}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a2eaafcdde24b4bb884914e28f5cc66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":802}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u23.png"}},
{
          "id":"cd3d16914ef249bba11091e708e11cc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf1e6eda169b4757a341f8b6487b43d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u39.png"}},
{
          "id":"83db259de3f744e0881e1f1731cac36b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"676a3406760641ed93af7ea05c13d233",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u41.png"}},
{
          "id":"7ebb70553e594987ad2e6349830a6029",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cbe53ea4078d4aa4bebbb9e82ff97cb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f977e6e9bf407a9678112fc9bdb299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":305,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"0c2581996bbe46338ab26b420253fbf3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":244,
              "y":145},
            "size":{
              "width":90,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"96703bfb98f74434b75cb49b15514654",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":148.5,
              "y":42},
            "size":{
              "width":360,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b83008c881c943fab8329092be98ba85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148.5,
                  "y":42},
                "size":{
                  "width":360,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u28.png"}},
{
          "id":"a3c462155c2043adbde1c5d4ac18a2de",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":750},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"da0c7b3249544c5693aca5c42464c00f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":820},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf964345560e4b9dbf44dcf45fe3e37c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":820},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"7897de7db48a426da50f8b226735596f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1011,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae22021ae4b45b6a0bed52bf8cd2d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1011,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u43.png"}},
{
          "id":"5dc593145a2a4f3f840544a9b55308f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1240,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f114e438b842658756df60f1f90d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1240,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u45.png"}},
{
          "id":"77a212153dec403e928b9a560336fc75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f2c104ef12a4c298221f370ddf5e0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u47.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "26d4539b226046d0a752f3718c53e2b3":{
      "scriptId":"u0"},
    "39969ff7aefb4fdd9ddd689561a4844c":{
      "scriptId":"u1"},
    "dcbd2d26df6944eda88f7c7bed928a04":{
      "scriptId":"u2"},
    "ba799350ecf142c7a8034b3b3e7756ca":{
      "scriptId":"u3"},
    "718fd469d85f43d38c1288a389d33dac":{
      "scriptId":"u4"},
    "bc165b97d2fe4f14a68cd10aa99e7126":{
      "scriptId":"u5"},
    "e91446421ba74b9baa7d176dc2524ba0":{
      "scriptId":"u6"},
    "c48424bd43f64f4897f5d6c578737d35":{
      "scriptId":"u7"},
    "e5ab48fabbed4fe2989dd334b1705e6f":{
      "scriptId":"u8"},
    "b439bb778844477b88b921433af745d2":{
      "scriptId":"u9"},
    "4bcc42ae984d4feba51990f35a85ae32":{
      "scriptId":"u10"},
    "f9dc86103c894bb8879a494f32a1282e":{
      "scriptId":"u11"},
    "3b60677a6ebb48cdaa8e9edbaca47584":{
      "scriptId":"u12"},
    "a5124196d61742fab02fc0671bb6c8d6":{
      "scriptId":"u13"},
    "80ea82a7032a441c901a5a94ca3c7511":{
      "scriptId":"u14"},
    "018955ef88bb456293a8f8dcf8ca86a5":{
      "scriptId":"u15"},
    "dbf27ab5a44d497fb374751f3a322d75":{
      "scriptId":"u16"},
    "6a8f6d861a1b46cda047989acbf043b3":{
      "scriptId":"u17"},
    "071b1ef058aa488c903682dd5830dd72":{
      "scriptId":"u18"},
    "615ff4fcd3914953accbca93c4d780f6":{
      "scriptId":"u19"},
    "7213ea3eb1f041348ed8afe98f28f146":{
      "scriptId":"u20"},
    "c323b425a24844c997d756dfbb7ac29d":{
      "scriptId":"u21"},
    "5205824ba1cd4630ae3a29d38e77a5b5":{
      "scriptId":"u22"},
    "5fcbe4f1b7c04c0baf0845ad5fe0182d":{
      "scriptId":"u23"},
    "f3723752eb7d4e499d17a9e3485b5ff4":{
      "scriptId":"u24"},
    "b9fa61c809d34e24b358c750d483497a":{
      "scriptId":"u25"},
    "79d6f14239e946d7ba94348aca83c50c":{
      "scriptId":"u26"},
    "13c70435a6b440c4a3e1ca98e54046af":{
      "scriptId":"u27"},
    "f9a4616d4f8f4c85b068d5815f0ec3db":{
      "scriptId":"u28"},
    "f43402ea02464d48b5bc31caf7ba347a":{
      "scriptId":"u29"},
    "1ad582c51de849ff8e2a5cd5997c2f83":{
      "scriptId":"u30"},
    "3a2eaafcdde24b4bb884914e28f5cc66":{
      "scriptId":"u31"},
    "cd3d16914ef249bba11091e708e11cc5":{
      "scriptId":"u32"},
    "bf1e6eda169b4757a341f8b6487b43d6":{
      "scriptId":"u33"},
    "83db259de3f744e0881e1f1731cac36b":{
      "scriptId":"u34"},
    "676a3406760641ed93af7ea05c13d233":{
      "scriptId":"u35"},
    "7ebb70553e594987ad2e6349830a6029":{
      "scriptId":"u36"},
    "cbe53ea4078d4aa4bebbb9e82ff97cb2":{
      "scriptId":"u37"},
    "b8f977e6e9bf407a9678112fc9bdb299":{
      "scriptId":"u38"},
    "0c2581996bbe46338ab26b420253fbf3":{
      "scriptId":"u39"},
    "96703bfb98f74434b75cb49b15514654":{
      "scriptId":"u40"},
    "b83008c881c943fab8329092be98ba85":{
      "scriptId":"u41"},
    "a3c462155c2043adbde1c5d4ac18a2de":{
      "scriptId":"u42"},
    "da0c7b3249544c5693aca5c42464c00f":{
      "scriptId":"u43"},
    "cf964345560e4b9dbf44dcf45fe3e37c":{
      "scriptId":"u44"},
    "7897de7db48a426da50f8b226735596f":{
      "scriptId":"u45"},
    "9ae22021ae4b45b6a0bed52bf8cd2d6b":{
      "scriptId":"u46"},
    "5dc593145a2a4f3f840544a9b55308f6":{
      "scriptId":"u47"},
    "22f114e438b842658756df60f1f90d2a":{
      "scriptId":"u48"},
    "77a212153dec403e928b9a560336fc75":{
      "scriptId":"u49"},
    "6f2c104ef12a4c298221f370ddf5e0b9":{
      "scriptId":"u50"}}});