$axure.loadCurrentPage({
  "url":"定制需求.html",
  "generationDate":new Date(1479704709022.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d008130c329c4518ae0d49dcb1684790",
    "type":"Axure:Page",
    "name":"定制需求",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b55d5f7044a847efa6fdedf20c95d455",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2236d7959754c788c047725df208a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"1d99724692444acdb6ff8e9937a187a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"343a019930424399b35a2399f7de6ae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定制需求/u2.jpg"}},
{
          "id":"ba5c454b8e0b470f86e1599b21a7a2aa",
          "label":"固定点",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":115,
              "y":72},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":115,
          "fixedVertical":"top",
          "fixedMarginVertical":72,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e91039632fb843a792fc17546ae246e3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2b08c546a8b3438badbb3b8430f6f260",
                  "label":"",
                  "parentDynamicPanel":"ba5c454b8e0b470f86e1599b21a7a2aa",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6e09c4151c64582b64062d8c0c8de6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ba5c454b8e0b470f86e1599b21a7a2aa",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/详情页/u10.png"}}]}]},
{
          "id":"fcea9fbb2e2a4d178d0f0e5d807142b2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":130},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 预约设计师",
                      "target":{
                        "targetType":"page",
                        "url":"预约设计师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b04f292cf4734bf581ea72c343c97da6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":410},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 上门量房",
                      "target":{
                        "targetType":"page",
                        "url":"上门量房.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6a7434cf721f428799b20fd0af748854",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":540},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐一",
                      "target":{
                        "targetType":"page",
                        "url":"套餐一.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ccb1b9e665b64662b63423064020c216",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":680},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐二",
                      "target":{
                        "targetType":"page",
                        "url":"套餐二.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"74d3d240a3824728aa32d7c2a7b626c0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":726},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-方案",
                      "target":{
                        "targetType":"page",
                        "url":"首页-方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8125315241c740f0a4318d206acb916b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":726},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新家--案例",
                      "target":{
                        "targetType":"page",
                        "url":"新家--案例.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e8740a5c856c4da2860d487ca8836895",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":726},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "b55d5f7044a847efa6fdedf20c95d455":{
      "scriptId":"u0"},
    "c2236d7959754c788c047725df208a23":{
      "scriptId":"u1"},
    "1d99724692444acdb6ff8e9937a187a6":{
      "scriptId":"u2"},
    "343a019930424399b35a2399f7de6ae3":{
      "scriptId":"u3"},
    "ba5c454b8e0b470f86e1599b21a7a2aa":{
      "scriptId":"u4"},
    "2b08c546a8b3438badbb3b8430f6f260":{
      "scriptId":"u5"},
    "f6e09c4151c64582b64062d8c0c8de6e":{
      "scriptId":"u6"},
    "fcea9fbb2e2a4d178d0f0e5d807142b2":{
      "scriptId":"u7"},
    "b04f292cf4734bf581ea72c343c97da6":{
      "scriptId":"u8"},
    "6a7434cf721f428799b20fd0af748854":{
      "scriptId":"u9"},
    "ccb1b9e665b64662b63423064020c216":{
      "scriptId":"u10"},
    "74d3d240a3824728aa32d7c2a7b626c0":{
      "scriptId":"u11"},
    "8125315241c740f0a4318d206acb916b":{
      "scriptId":"u12"},
    "e8740a5c856c4da2860d487ca8836895":{
      "scriptId":"u13"}}});