$axure.loadCurrentPage({
  "url":"教程页.html",
  "generationDate":new Date(1488665387235.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ffd3a11d52504600883f75d2bd84e246",
    "type":"Axure:Page",
    "name":"教程页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02a2b20a15cc471cb5a43e82dce3f9fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49da0b4d93634e278641cdc56dedbe21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教程页/u0.png"}},
{
          "id":"2737929418934cbaab3ff3ebf54c5f15",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":730},
            "size":{
              "width":90,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"281bad885b1d4df2aae628b5ddf7df6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":740},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd7ed8d24bb4478a99aaabdbd59c0f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":830,
                  "y":740},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "02a2b20a15cc471cb5a43e82dce3f9fc":{
      "scriptId":"u0"},
    "49da0b4d93634e278641cdc56dedbe21":{
      "scriptId":"u1"},
    "2737929418934cbaab3ff3ebf54c5f15":{
      "scriptId":"u2"},
    "281bad885b1d4df2aae628b5ddf7df6d":{
      "scriptId":"u3"},
    "cd7ed8d24bb4478a99aaabdbd59c0f31":{
      "scriptId":"u4"}}});