$axure.loadCurrentPage({
  "url":"我的消息.html",
  "generationDate":new Date(1479704710604.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0f720a71a1364a8aa33069dc83d6a0e7",
    "type":"Axure:Page",
    "name":"我的消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"06375dca2aa6427d8d44d5c7c3bf470f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a086e7cb87c144058818b9a3550c238f"},
{
          "id":"d5f0a12807a0437493034e81ff04cb32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":104},
            "size":{
              "width":374,
              "height":669}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5920b70f07c645e88448799134a28468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":104},
                "size":{
                  "width":374,
                  "height":669}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的消息/u3.png"}},
{
          "id":"87d390fa3b4f4a2eb51475c2dfb3b9ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":104},
            "size":{
              "width":374,
              "height":669}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2d8875701d4ac484fb565c671c6e3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":104},
                "size":{
                  "width":374,
                  "height":669}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的消息/u5.png"}},
{
          "id":"581a3c57ff0f4561817a19ec46c06203",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":132},
            "size":{
              "width":32,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "a086e7cb87c144058818b9a3550c238f":{
      "packageId":"a086e7cb87c144058818b9a3550c238f",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"623c214f22b644b990c3bc1c0a100f4d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":430,
                "height":880}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7feffeea2daa4300973110505dfb8fb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":430,
                    "height":880}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/app/u1.jpg"}}]}}},
  "objectPaths":{
    "06375dca2aa6427d8d44d5c7c3bf470f":{
      "scriptId":"u0",
      "623c214f22b644b990c3bc1c0a100f4d":{
        "scriptId":"u1"},
      "7feffeea2daa4300973110505dfb8fb0":{
        "scriptId":"u2"}},
    "d5f0a12807a0437493034e81ff04cb32":{
      "scriptId":"u3"},
    "5920b70f07c645e88448799134a28468":{
      "scriptId":"u4"},
    "87d390fa3b4f4a2eb51475c2dfb3b9ba":{
      "scriptId":"u5"},
    "5a2d8875701d4ac484fb565c671c6e3f":{
      "scriptId":"u6"},
    "581a3c57ff0f4561817a19ec46c06203":{
      "scriptId":"u7"}}});