$axure.loadCurrentPage({
  "url":"素材库.html",
  "generationDate":new Date(1488665387897.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a710985dc2e04ea8813874900bfd1030",
    "type":"Axure:Page",
    "name":"素材库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd60d6a66f1c45c899e479ce73ce9ab6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"829b2afd94364893b421202120882916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/素材库/u0.png"}},
{
          "id":"57913beb684d4be18686b1328f7acaf7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd6c73aa248a44e5bdb0a62c038d193a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u2.png"}},
{
          "id":"b1f554b10e534e4095745096314b3c5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41be5e8b8691437a8d6c3236818e5727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u4.png"}},
{
          "id":"136898f1c1ab4541858b5c4155ece9da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1547,
              "y":21},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eba1afef9194fcc829ee6262f0f0afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1547,
                  "y":21},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/素材库/u6.png"}},
{
          "id":"9475a5a316ef4ac198a7e70190d3016e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":134},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐方案",
                      "target":{
                        "targetType":"page",
                        "url":"套餐方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6493fd0e628848ed86d638d8f23323e2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":284},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收藏",
                      "target":{
                        "targetType":"page",
                        "url":"收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"58f532dac0264e359712f53489e9b446",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3728ba97c4c04da7b6001f20d7aff97a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":801}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5202423b0186479aa504bf0b993dae1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":801}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐配置/u12.png"}},
{
          "id":"98d7e78023bb401fa1b58f6533c703b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":135.66667175293},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9227487fd1544591a47e2413d41613cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":135.66667175293},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐方案",
                      "target":{
                        "targetType":"page",
                        "url":"套餐方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"f0f1d41cfcec42cba09f6831185638f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"817b05c34f3049439b54aa6a8f6c072e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"de80d121cf3143e9a0d6b8c4c9a51d9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":285},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67cf73512fd546dfa7b591b05f1ef1c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":285},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收藏",
                      "target":{
                        "targetType":"page",
                        "url":"收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"85eb75f13fec4d448f80e28c2a133055",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":54},
            "size":{
              "width":123,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4281410f87f947aa9258adedbe50c875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":54},
                "size":{
                  "width":123,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u6.png"}},
{
          "id":"f29e9b8e67a0452b9ee37281606be36d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":802}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b829aa9364d44ff8e63292d8eee217f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":802}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u23.png"}},
{
          "id":"e60aa7deb4cc44f8a1e8f1a7ef45c6f9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":47},
            "size":{
              "width":66,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0a22de52ed184e6e9734842ded427872",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1470,
              "y":59},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51db1fafe04f4dcc8a1522528edeefe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1470,
                  "y":59},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"8bad2e66eed944f481943eb109aa3929",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":802}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f67b327c0489466c9bdf24e901e8ac36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":802}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u23.png"}},
{
          "id":"460865c81c20408c96c83e7b3a4ff6d4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a5a1278b686b48a2bb8ff8d06f887af8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90d35f63de094011a89889e846d05602",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":305,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"2ee1c944b57f442da830b58d9183e032",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":148.5,
              "y":42},
            "size":{
              "width":360,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2237eed8f63e4406824ff40288ee96db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148.5,
                  "y":42},
                "size":{
                  "width":360,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u28.png"}},
{
          "id":"89bbccb928a64d69898530f8fa8cbeca",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":750},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6c122c9a34a6490b9161fe1c9b083a0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":820},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c1b83967d97460d9761b6992d772a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":820},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"27885718109f4bbcb4378413a579aac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4B5161},
            "location":{
              "x":2,
              "y":136},
            "size":{
              "width":46,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88a11a41f36940b393a7669bda15e0ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4B5161},
                "location":{
                  "x":2,
                  "y":136},
                "size":{
                  "width":46,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u33.png"}},
{
          "id":"f31976957f1a47c5a00280dc8867f3c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":196.5},
            "size":{
              "width":37,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b73fbf0ed064f46adfecf1cac106c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":196.5},
                "size":{
                  "width":37,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eb4044c415948f38862d2a61509f740",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":147},
            "size":{
              "width":37,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c6dbadddfbf46f388455e311f6886cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":147},
                "size":{
                  "width":37,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ab0513de3a94ccda0b9edf1546561d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ce1aeffb1149f7abab41228c026460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u39.png"}},
{
          "id":"ba746d44a1b6410b95ac786afe6a5c92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1f220a729004cf29ec15f6c43ae9971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u41.png"}},
{
          "id":"ffba1133e2b143aeb0fa540284732685",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1011,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fae6a7beb7c40c48c24927e7d8cd2a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1011,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u43.png"}},
{
          "id":"1f9f1af6fc6549eabdde0b813870dbb8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1240,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de74a49ab1644dcba57572d4453c0029",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1240,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u45.png"}},
{
          "id":"3bedd2f6f86942798dfae4792673fa85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"478c4d9d95074b84aae830cfde77c277",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u47.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bd60d6a66f1c45c899e479ce73ce9ab6":{
      "scriptId":"u0"},
    "829b2afd94364893b421202120882916":{
      "scriptId":"u1"},
    "57913beb684d4be18686b1328f7acaf7":{
      "scriptId":"u2"},
    "fd6c73aa248a44e5bdb0a62c038d193a":{
      "scriptId":"u3"},
    "b1f554b10e534e4095745096314b3c5f":{
      "scriptId":"u4"},
    "41be5e8b8691437a8d6c3236818e5727":{
      "scriptId":"u5"},
    "136898f1c1ab4541858b5c4155ece9da":{
      "scriptId":"u6"},
    "9eba1afef9194fcc829ee6262f0f0afd":{
      "scriptId":"u7"},
    "9475a5a316ef4ac198a7e70190d3016e":{
      "scriptId":"u8"},
    "6493fd0e628848ed86d638d8f23323e2":{
      "scriptId":"u9"},
    "58f532dac0264e359712f53489e9b446":{
      "scriptId":"u10"},
    "3728ba97c4c04da7b6001f20d7aff97a":{
      "scriptId":"u11"},
    "5202423b0186479aa504bf0b993dae1b":{
      "scriptId":"u12"},
    "98d7e78023bb401fa1b58f6533c703b6":{
      "scriptId":"u13"},
    "9227487fd1544591a47e2413d41613cf":{
      "scriptId":"u14"},
    "f0f1d41cfcec42cba09f6831185638f1":{
      "scriptId":"u15"},
    "817b05c34f3049439b54aa6a8f6c072e":{
      "scriptId":"u16"},
    "de80d121cf3143e9a0d6b8c4c9a51d9f":{
      "scriptId":"u17"},
    "67cf73512fd546dfa7b591b05f1ef1c5":{
      "scriptId":"u18"},
    "85eb75f13fec4d448f80e28c2a133055":{
      "scriptId":"u19"},
    "4281410f87f947aa9258adedbe50c875":{
      "scriptId":"u20"},
    "f29e9b8e67a0452b9ee37281606be36d":{
      "scriptId":"u21"},
    "7b829aa9364d44ff8e63292d8eee217f":{
      "scriptId":"u22"},
    "e60aa7deb4cc44f8a1e8f1a7ef45c6f9":{
      "scriptId":"u23"},
    "0a22de52ed184e6e9734842ded427872":{
      "scriptId":"u24"},
    "51db1fafe04f4dcc8a1522528edeefe3":{
      "scriptId":"u25"},
    "8bad2e66eed944f481943eb109aa3929":{
      "scriptId":"u26"},
    "f67b327c0489466c9bdf24e901e8ac36":{
      "scriptId":"u27"},
    "460865c81c20408c96c83e7b3a4ff6d4":{
      "scriptId":"u28"},
    "a5a1278b686b48a2bb8ff8d06f887af8":{
      "scriptId":"u29"},
    "90d35f63de094011a89889e846d05602":{
      "scriptId":"u30"},
    "2ee1c944b57f442da830b58d9183e032":{
      "scriptId":"u31"},
    "2237eed8f63e4406824ff40288ee96db":{
      "scriptId":"u32"},
    "89bbccb928a64d69898530f8fa8cbeca":{
      "scriptId":"u33"},
    "6c122c9a34a6490b9161fe1c9b083a0c":{
      "scriptId":"u34"},
    "3c1b83967d97460d9761b6992d772a73":{
      "scriptId":"u35"},
    "27885718109f4bbcb4378413a579aac6":{
      "scriptId":"u36"},
    "88a11a41f36940b393a7669bda15e0ab":{
      "scriptId":"u37"},
    "f31976957f1a47c5a00280dc8867f3c7":{
      "scriptId":"u38"},
    "4b73fbf0ed064f46adfecf1cac106c2b":{
      "scriptId":"u39"},
    "1eb4044c415948f38862d2a61509f740":{
      "scriptId":"u40"},
    "7c6dbadddfbf46f388455e311f6886cc":{
      "scriptId":"u41"},
    "5ab0513de3a94ccda0b9edf1546561d6":{
      "scriptId":"u42"},
    "25ce1aeffb1149f7abab41228c026460":{
      "scriptId":"u43"},
    "ba746d44a1b6410b95ac786afe6a5c92":{
      "scriptId":"u44"},
    "d1f220a729004cf29ec15f6c43ae9971":{
      "scriptId":"u45"},
    "ffba1133e2b143aeb0fa540284732685":{
      "scriptId":"u46"},
    "0fae6a7beb7c40c48c24927e7d8cd2a1":{
      "scriptId":"u47"},
    "1f9f1af6fc6549eabdde0b813870dbb8":{
      "scriptId":"u48"},
    "de74a49ab1644dcba57572d4453c0029":{
      "scriptId":"u49"},
    "3bedd2f6f86942798dfae4792673fa85":{
      "scriptId":"u50"},
    "478c4d9d95074b84aae830cfde77c277":{
      "scriptId":"u51"}}});