$axure.loadCurrentPage({
  "url":"我的.html",
  "generationDate":new Date(1479704710087.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9bbac7fde3b94542ac227e4d40ccfa4d",
    "type":"Axure:Page",
    "name":"我的",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3630f3eb7e5b48d682a90f8953f86b6e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a086e7cb87c144058818b9a3550c238f"},
{
          "id":"acd9d52d5c97443c9549c3aa4a9cc077",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac6126b7b7c4b13b95d46014334e896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的/u3.jpg"}},
{
          "id":"1ebf19fad4864a9cac0cc20dbaa5cf02",
          "label":"登录、注册热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":177,
              "y":204},
            "size":{
              "width":78,
              "height":106}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"02ec638780b141729860841dfee12527",
          "label":"设置热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":137},
            "size":{
              "width":27,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ab9bd29ae3994d929219c00b8c702894",
          "label":"我的预约热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28.5,
              "y":370},
            "size":{
              "width":373,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的预约",
                      "target":{
                        "targetType":"page",
                        "url":"我的预约.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8207127699184413807bb9f3bf71518e",
          "label":"我的工期热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":419},
            "size":{
              "width":373,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的工期",
                      "target":{
                        "targetType":"page",
                        "url":"我的工期.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2f4b154c37144b23b4d15144690a672b",
          "label":"我的收藏热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":470},
            "size":{
              "width":373,
              "height":43}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的收藏",
                      "target":{
                        "targetType":"page",
                        "url":"我的收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3d9f74daffc64d9d984c5c27cc3fdac8",
          "label":"我的消息热区",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":520},
            "size":{
              "width":373,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的消息",
                      "target":{
                        "targetType":"page",
                        "url":"我的消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2ce659bff1314cf486ea6b9eb1d5d9b5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":725},
            "size":{
              "width":67,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新家--进程",
                      "target":{
                        "targetType":"page",
                        "url":"新家--进程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b9573184aa2145978b0b8f787562d7b9",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":725},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 定制需求",
                      "target":{
                        "targetType":"page",
                        "url":"定制需求.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"649db8f419df48528b716a172fb7702a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":725},
            "size":{
              "width":80,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-方案",
                      "target":{
                        "targetType":"page",
                        "url":"首页-方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "a086e7cb87c144058818b9a3550c238f":{
      "packageId":"a086e7cb87c144058818b9a3550c238f",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"623c214f22b644b990c3bc1c0a100f4d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":430,
                "height":880}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7feffeea2daa4300973110505dfb8fb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":430,
                    "height":880}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/app/u1.jpg"}}]}}},
  "objectPaths":{
    "3630f3eb7e5b48d682a90f8953f86b6e":{
      "scriptId":"u0",
      "623c214f22b644b990c3bc1c0a100f4d":{
        "scriptId":"u1"},
      "7feffeea2daa4300973110505dfb8fb0":{
        "scriptId":"u2"}},
    "acd9d52d5c97443c9549c3aa4a9cc077":{
      "scriptId":"u3"},
    "9ac6126b7b7c4b13b95d46014334e896":{
      "scriptId":"u4"},
    "1ebf19fad4864a9cac0cc20dbaa5cf02":{
      "scriptId":"u5"},
    "02ec638780b141729860841dfee12527":{
      "scriptId":"u6"},
    "ab9bd29ae3994d929219c00b8c702894":{
      "scriptId":"u7"},
    "8207127699184413807bb9f3bf71518e":{
      "scriptId":"u8"},
    "2f4b154c37144b23b4d15144690a672b":{
      "scriptId":"u9"},
    "3d9f74daffc64d9d984c5c27cc3fdac8":{
      "scriptId":"u10"},
    "2ce659bff1314cf486ea6b9eb1d5d9b5":{
      "scriptId":"u11"},
    "b9573184aa2145978b0b8f787562d7b9":{
      "scriptId":"u12"},
    "649db8f419df48528b716a172fb7702a":{
      "scriptId":"u13"}}});