$axure.loadCurrentPage({
  "url":"启动界面.html",
  "generationDate":new Date(1488665386826.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2695597cab2a44e7949ff02f57184688",
    "type":"Axure:Page",
    "name":"启动界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3a80516fb05442ef9bf0311c42c9d13d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":144},
            "size":{
              "width":1284,
              "height":812}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cffc077ceeca4dc6b3fe8071acbbff96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":144},
                "size":{
                  "width":1284,
                  "height":812}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u0.png"}},
{
          "id":"8bc22f19e47042c9bdcce487901b1b20",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1075,
              "y":710},
            "size":{
              "width":108,
              "height":47}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册登录",
                      "target":{
                        "targetType":"page",
                        "url":"注册登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eb1c5a0a3e8d49d09a8298712f540a3a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":977,
              "y":370},
            "size":{
              "width":40,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 https://www.rayion.com/",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.rayion.com/",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"20c2db8deea04764b93c1bdcb6f8aca9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1083.20007324219,
              "y":716.799987792969},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995f77cdeff74f919d4999b877c515dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1083.20007324219,
                  "y":716.799987792969},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"337e213516d9460aa3ff2a0c18043249",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":375},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cafa8b825d6c401b98f58e6673d51c6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":980,
                  "y":375},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3a80516fb05442ef9bf0311c42c9d13d":{
      "scriptId":"u0"},
    "cffc077ceeca4dc6b3fe8071acbbff96":{
      "scriptId":"u1"},
    "8bc22f19e47042c9bdcce487901b1b20":{
      "scriptId":"u2"},
    "eb1c5a0a3e8d49d09a8298712f540a3a":{
      "scriptId":"u3"},
    "20c2db8deea04764b93c1bdcb6f8aca9":{
      "scriptId":"u4"},
    "995f77cdeff74f919d4999b877c515dd":{
      "scriptId":"u5"},
    "337e213516d9460aa3ff2a0c18043249":{
      "scriptId":"u6"},
    "cafa8b825d6c401b98f58e6673d51c6d":{
      "scriptId":"u7"}}});