$axure.loadCurrentPage({
  "url":"意见反馈.html",
  "generationDate":new Date(1479704710319.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1dafd0bfdcff474eadc2beb3b6bc1983",
    "type":"Axure:Page",
    "name":"意见反馈",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a01b9b1af27841649eefaeb265294f83",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"a086e7cb87c144058818b9a3550c238f"},
{
          "id":"da0eb08d23104847b06387cefd87cc86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":374,
              "height":666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bccabe4017bc4d91a2318d3bfe91abc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":374,
                  "height":666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/意见反馈/u3.png"}},
{
          "id":"5b482898caf64b028134cfcd64659664",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":130},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置",
                      "target":{
                        "targetType":"page",
                        "url":"设置.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1ea177a0cd2145c8a652832885cffae7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":130},
            "size":{
              "width":38,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 提交成功",
                      "objectsToFades":[{
                          "objectPath":["57fc8f7010bc4fa38dff07c264b5664e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待1000毫秒",
                      "waitTime":1000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 提交成功",
                      "objectsToFades":[{
                          "objectPath":["57fc8f7010bc4fa38dff07c264b5664e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"57fc8f7010bc4fa38dff07c264b5664e",
          "label":"提交成功",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":110,
              "y":340},
            "size":{
              "width":200,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c44ea83519d2411a8263a2b63a6e52b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":110,
                  "y":340},
                "size":{
                  "width":200,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分享/u6.png"}}]}},
  "masters":{
    "a086e7cb87c144058818b9a3550c238f":{
      "packageId":"a086e7cb87c144058818b9a3550c238f",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"623c214f22b644b990c3bc1c0a100f4d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":430,
                "height":880}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7feffeea2daa4300973110505dfb8fb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":430,
                    "height":880}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/app/u1.jpg"}}]}}},
  "objectPaths":{
    "a01b9b1af27841649eefaeb265294f83":{
      "scriptId":"u0",
      "623c214f22b644b990c3bc1c0a100f4d":{
        "scriptId":"u1"},
      "7feffeea2daa4300973110505dfb8fb0":{
        "scriptId":"u2"}},
    "da0eb08d23104847b06387cefd87cc86":{
      "scriptId":"u3"},
    "bccabe4017bc4d91a2318d3bfe91abc1":{
      "scriptId":"u4"},
    "5b482898caf64b028134cfcd64659664":{
      "scriptId":"u5"},
    "1ea177a0cd2145c8a652832885cffae7":{
      "scriptId":"u6"},
    "57fc8f7010bc4fa38dff07c264b5664e":{
      "scriptId":"u7"},
    "c44ea83519d2411a8263a2b63a6e52b2":{
      "scriptId":"u8"}}});