$axure.loadCurrentPage({
  "url":"中级-立即预约.html",
  "generationDate":new Date(1479704709225.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"64947299ea004fb1a6d0459701be5801",
    "type":"Axure:Page",
    "name":"中级-立即预约",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"05fec430e8db4bcabf70686a07504734",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815789839f0446c0a7f336060a2211f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"8fb6dfdced35437bb41b3a47b8126ef1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"924c267784fb4590a36107ab957b950e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/立即预约-上门量房/u2.png"}},
{
          "id":"3de34e1cb53848c8a1ec7ac00b8a89fb",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":130},
            "size":{
              "width":43,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 中级设计套餐",
                      "target":{
                        "targetType":"page",
                        "url":"中级设计套餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"25d5c5a3f1e34661b41cfb0025d603f4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":130},
            "size":{
              "width":72,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算",
                      "target":{
                        "targetType":"page",
                        "url":"结算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "05fec430e8db4bcabf70686a07504734":{
      "scriptId":"u0"},
    "815789839f0446c0a7f336060a2211f4":{
      "scriptId":"u1"},
    "8fb6dfdced35437bb41b3a47b8126ef1":{
      "scriptId":"u2"},
    "924c267784fb4590a36107ab957b950e":{
      "scriptId":"u3"},
    "3de34e1cb53848c8a1ec7ac00b8a89fb":{
      "scriptId":"u4"},
    "25d5c5a3f1e34661b41cfb0025d603f4":{
      "scriptId":"u5"}}});