$axure.loadCurrentPage({
  "url":"首页-方案.html",
  "generationDate":new Date(1479704708430.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54d755ec86194ba8a06492bd53b43ff0",
    "type":"Axure:Page",
    "name":"首页-方案",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8d32268281764d46a1fcb04bb4a2ba17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc3c51f59ea84de2bd8178255f3cb3a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"093343b8afa540b3a3ee2404065f93bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b05bb0e2d3ac44b597d4dddd00759eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-方案/u2.jpg"}},
{
          "id":"153ce5e79ed44507a4ea264967bb7782",
          "label":"素雅清新风",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":214},
            "size":{
              "width":371,
              "height":238}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 详情页",
                      "target":{
                        "targetType":"page",
                        "url":"详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3b7e1f677ead4df5a77146f5eb608830",
          "label":"黑色阴影",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F333333},
            "location":{
              "x":27,
              "y":106},
            "size":{
              "width":375,
              "height":670},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab9efab5c30f40a2a982279776b5ac82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F333333},
                "location":{
                  "x":27,
                  "y":106},
                "size":{
                  "width":375,
                  "height":670},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 黑色阴影,<br>风格选择,<br>面积选择,<br>空间选择 淡入淡出 500 ms,<br>(动态面板),<br>(形状),<br>(动态面板),<br>(动态面板),<br>(动态面板),<br>定位",
                      "objectsToFades":[{
                          "objectPath":["3b7e1f677ead4df5a77146f5eb608830"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["864c9b40fb5546988b9a4b7a627caaf2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b2bffc9bf7184aa9ac7b695c8c77500a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b3a4874a716744fb9c20b69e30ebf48e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["5325dd3499584922b617447dd08df0b7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a16dd5d60f064252820fa7b12fdedabe"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["47e4d76d84ae4cc5be5fd86087a6b7c5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["80f3365a5d5a4667961b5e058bc20bb6"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7c215a4468d14cbe842a9661bf511ddc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["345f4a831950434e94203a79b1011edb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-方案/黑色阴影_u5.png"}},
{
          "id":"5325dd3499584922b617447dd08df0b7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":178},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f0ce71b0a4a94cdf8efc2c3057e81b48",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"864c9b40fb5546988b9a4b7a627caaf2",
                  "label":"风格选择",
                  "parentDynamicPanel":"5325dd3499584922b617447dd08df0b7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":375,
                      "height":214},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa6e420ad0224f58bfbe093647235e51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5325dd3499584922b617447dd08df0b7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":375,
                          "height":214},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-方案/风格选择_u8.png"}},
{
                  "id":"a16dd5d60f064252820fa7b12fdedabe",
                  "label":"",
                  "parentDynamicPanel":"5325dd3499584922b617447dd08df0b7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
},
                      "mouseDown":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF47C5C1}}},
                    "location":{
                      "x":137,
                      "y":47},
                    "size":{
                      "width":101,
                      "height":30},
                    "visible":false,
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b59b6e294d84082a05c5db0ce36309b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5325dd3499584922b617447dd08df0b7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
},
                          "mouseDown":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF47C5C1}}},
                        "location":{
                          "x":137,
                          "y":47},
                        "size":{
                          "width":101,
                          "height":30},
                        "visible":false,
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 主页",
                              "target":{
                                "targetType":"page",
                                "url":"主页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页-方案/u10.png",
                    "mouseDown~":"images/首页-方案/u10_mouseDown.png"}}]}]},
{
          "id":"47e4d76d84ae4cc5be5fd86087a6b7c5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":178},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2d1faf867bb5403894d1d9a4f81b4b79",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b2bffc9bf7184aa9ac7b695c8c77500a",
                  "label":"面积选择",
                  "parentDynamicPanel":"47e4d76d84ae4cc5be5fd86087a6b7c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":375,
                      "height":137},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ee6f69635b2457f89e455239eb6bab2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"47e4d76d84ae4cc5be5fd86087a6b7c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":375,
                          "height":137},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-方案/面积选择_u13.png"}}]}]},
{
          "id":"80f3365a5d5a4667961b5e058bc20bb6",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":177},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7d81ae1361254a3f98663db9ed33e4c8",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b3a4874a716744fb9c20b69e30ebf48e",
                  "label":"空间选择",
                  "parentDynamicPanel":"80f3365a5d5a4667961b5e058bc20bb6",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":375,
                      "height":213},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cfa35bd41b5341d7b076515b5d747d58",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"80f3365a5d5a4667961b5e058bc20bb6",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":375,
                          "height":213},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-方案/空间选择_u16.png"}}]}]},
{
          "id":"d25113c907c04a43912765e37c3e7d3e",
          "label":"定位",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":34,
              "y":132},
            "size":{
              "width":41,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 (动态面板),<br>定位,<br>黑色阴影",
                      "objectsToFades":[{
                          "objectPath":["7c215a4468d14cbe842a9661bf511ddc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["345f4a831950434e94203a79b1011edb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["3b7e1f677ead4df5a77146f5eb608830"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"65821ece32544abc8f546045bc529376",
          "label":"搜索",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":352,
              "y":129},
            "size":{
              "width":46,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 搜索",
                      "target":{
                        "targetType":"page",
                        "url":"搜索.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a758d1074d52465ebad6b312751ebb00",
          "label":"风格",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":180},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 面积选择,<br>空间选择",
                      "objectsToFades":[{
                          "objectPath":["b2bffc9bf7184aa9ac7b695c8c77500a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b3a4874a716744fb9c20b69e30ebf48e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 黑色阴影,<br>(动态面板),<br>风格选择,<br>(形状)",
                      "objectsToFades":[{
                          "objectPath":["3b7e1f677ead4df5a77146f5eb608830"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5325dd3499584922b617447dd08df0b7"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["864c9b40fb5546988b9a4b7a627caaf2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["a16dd5d60f064252820fa7b12fdedabe"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"beeff9310f474eb1a19f93fc2bb2ba72",
          "label":"面积",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":180},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 空间选择,<br>(动态面板)",
                      "objectsToFades":[{
                          "objectPath":["b3a4874a716744fb9c20b69e30ebf48e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5325dd3499584922b617447dd08df0b7"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 面积选择 淡入淡出 500 ms,<br>黑色阴影,<br>(动态面板)",
                      "objectsToFades":[{
                          "objectPath":["b2bffc9bf7184aa9ac7b695c8c77500a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["3b7e1f677ead4df5a77146f5eb608830"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["47e4d76d84ae4cc5be5fd86087a6b7c5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"3f26c7863d9d4115bec78a0c98cf35fc",
          "label":"空间",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":180},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 风格选择,<br>面积选择",
                      "objectsToFades":[{
                          "objectPath":["864c9b40fb5546988b9a4b7a627caaf2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b2bffc9bf7184aa9ac7b695c8c77500a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 空间选择 淡入淡出 500 ms,<br>黑色阴影,<br>(动态面板)",
                      "objectsToFades":[{
                          "objectPath":["b3a4874a716744fb9c20b69e30ebf48e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}},
{
                          "objectPath":["3b7e1f677ead4df5a77146f5eb608830"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["80f3365a5d5a4667961b5e058bc20bb6"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"14cb6524964a4778978b9d8c3a8c442d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":726},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 定制需求",
                      "target":{
                        "targetType":"page",
                        "url":"定制需求.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"2b1cfcdc00c041cd87578f91e46738b4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":726},
            "size":{
              "width":90,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新家--案例",
                      "target":{
                        "targetType":"page",
                        "url":"新家--案例.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b417c7dba5e64f3eafcbba80f5cb0d13",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":726},
            "size":{
              "width":82,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7c215a4468d14cbe842a9661bf511ddc",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":27,
              "y":177},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"68f92984b7154e54b89e70b8439f6b41",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"345f4a831950434e94203a79b1011edb",
                  "label":"定位",
                  "parentDynamicPanel":"7c215a4468d14cbe842a9661bf511ddc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":375,
                      "height":179},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"277d9567e55341b6b6cc00d52916df32",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7c215a4468d14cbe842a9661bf511ddc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "size":{
                          "width":375,
                          "height":179},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页-方案/定位_u27.png"}},
{
                  "id":"a5b8d1bceb0044aaac778a94e5151b03",
                  "label":"",
                  "parentDynamicPanel":"7c215a4468d14cbe842a9661bf511ddc",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":179,
                      "y":10},
                    "size":{
                      "width":50,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 (动态面板),<br>风格选择,<br>(形状),<br>(动态面板),<br>面积选择,<br>(动态面板),<br>空间选择,<br>黑色阴影,<br>(动态面板),<br>定位,<br>(Hot Spot)",
                              "objectsToFades":[{
                                  "objectPath":["5325dd3499584922b617447dd08df0b7"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["864c9b40fb5546988b9a4b7a627caaf2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["a16dd5d60f064252820fa7b12fdedabe"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["47e4d76d84ae4cc5be5fd86087a6b7c5"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b2bffc9bf7184aa9ac7b695c8c77500a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["80f3365a5d5a4667961b5e058bc20bb6"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["b3a4874a716744fb9c20b69e30ebf48e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["3b7e1f677ead4df5a77146f5eb608830"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["7c215a4468d14cbe842a9661bf511ddc"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["345f4a831950434e94203a79b1011edb"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["a5b8d1bceb0044aaac778a94e5151b03"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "8d32268281764d46a1fcb04bb4a2ba17":{
      "scriptId":"u0"},
    "cc3c51f59ea84de2bd8178255f3cb3a8":{
      "scriptId":"u1"},
    "093343b8afa540b3a3ee2404065f93bc":{
      "scriptId":"u2"},
    "b05bb0e2d3ac44b597d4dddd00759eba":{
      "scriptId":"u3"},
    "153ce5e79ed44507a4ea264967bb7782":{
      "scriptId":"u4"},
    "3b7e1f677ead4df5a77146f5eb608830":{
      "scriptId":"u5"},
    "ab9efab5c30f40a2a982279776b5ac82":{
      "scriptId":"u6"},
    "5325dd3499584922b617447dd08df0b7":{
      "scriptId":"u7"},
    "864c9b40fb5546988b9a4b7a627caaf2":{
      "scriptId":"u8"},
    "aa6e420ad0224f58bfbe093647235e51":{
      "scriptId":"u9"},
    "a16dd5d60f064252820fa7b12fdedabe":{
      "scriptId":"u10"},
    "7b59b6e294d84082a05c5db0ce36309b":{
      "scriptId":"u11"},
    "47e4d76d84ae4cc5be5fd86087a6b7c5":{
      "scriptId":"u12"},
    "b2bffc9bf7184aa9ac7b695c8c77500a":{
      "scriptId":"u13"},
    "5ee6f69635b2457f89e455239eb6bab2":{
      "scriptId":"u14"},
    "80f3365a5d5a4667961b5e058bc20bb6":{
      "scriptId":"u15"},
    "b3a4874a716744fb9c20b69e30ebf48e":{
      "scriptId":"u16"},
    "cfa35bd41b5341d7b076515b5d747d58":{
      "scriptId":"u17"},
    "d25113c907c04a43912765e37c3e7d3e":{
      "scriptId":"u18"},
    "65821ece32544abc8f546045bc529376":{
      "scriptId":"u19"},
    "a758d1074d52465ebad6b312751ebb00":{
      "scriptId":"u20"},
    "beeff9310f474eb1a19f93fc2bb2ba72":{
      "scriptId":"u21"},
    "3f26c7863d9d4115bec78a0c98cf35fc":{
      "scriptId":"u22"},
    "14cb6524964a4778978b9d8c3a8c442d":{
      "scriptId":"u23"},
    "2b1cfcdc00c041cd87578f91e46738b4":{
      "scriptId":"u24"},
    "b417c7dba5e64f3eafcbba80f5cb0d13":{
      "scriptId":"u25"},
    "7c215a4468d14cbe842a9661bf511ddc":{
      "scriptId":"u26"},
    "345f4a831950434e94203a79b1011edb":{
      "scriptId":"u27"},
    "277d9567e55341b6b6cc00d52916df32":{
      "scriptId":"u28"},
    "a5b8d1bceb0044aaac778a94e5151b03":{
      "scriptId":"u29"}}});