$axure.loadCurrentPage({
  "url":"基础-立即预约.html",
  "generationDate":new Date(1479704709170.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1e7890bf84cf4938aa066883cdc2405d",
    "type":"Axure:Page",
    "name":"基础-立即预约",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"834df8ba57694c51b5df0e07932bddf0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a844713b8b24808b01127b0d16c909a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"72f45412c9b341c58066704c769c92c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a241333a6a242eb9e0d4528d79f1331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/立即预约-上门量房/u2.png"}},
{
          "id":"8f959c62431547d39edb9630d8850cd6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":130},
            "size":{
              "width":72,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算",
                      "target":{
                        "targetType":"page",
                        "url":"结算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"17c6fb0babf44f1492f51c0122166ab4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":130},
            "size":{
              "width":43,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基础设计套餐",
                      "target":{
                        "targetType":"page",
                        "url":"基础设计套餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "834df8ba57694c51b5df0e07932bddf0":{
      "scriptId":"u0"},
    "8a844713b8b24808b01127b0d16c909a":{
      "scriptId":"u1"},
    "72f45412c9b341c58066704c769c92c3":{
      "scriptId":"u2"},
    "1a241333a6a242eb9e0d4528d79f1331":{
      "scriptId":"u3"},
    "8f959c62431547d39edb9630d8850cd6":{
      "scriptId":"u4"},
    "17c6fb0babf44f1492f51c0122166ab4":{
      "scriptId":"u5"}}});