$axure.loadCurrentPage({
  "url":"详情页.html",
  "generationDate":new Date(1479704708660.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"49c45bf14d654bf3ac69fe3fe0dde46c",
    "type":"Axure:Page",
    "name":"详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b55d5f7044a847efa6fdedf20c95d455",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2236d7959754c788c047725df208a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"7e6e4d5dd41c482597158bd0f813b4cf",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":108},
            "size":{
              "width":375,
              "height":665}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f0ddda33f02548b08bca31d46813dc35",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1390fdffb5134c4c92b75debd0320915",
                  "label":"",
                  "parentDynamicPanel":"7e6e4d5dd41c482597158bd0f813b4cf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":372,
                      "height":667}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3587f35ebf5f4c7aa369bbc799d58a2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7e6e4d5dd41c482597158bd0f813b4cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":372,
                          "height":667}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/详情页/u3.png"}},
{
                  "id":"ac765c0c9e2e4a969e47aa318e110047",
                  "label":"",
                  "parentDynamicPanel":"7e6e4d5dd41c482597158bd0f813b4cf",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onDrag":{
                      "description":"OnDrag",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 详情页 y 轴拖动",
                              "objectsToMoves":[{
                                  "objectPath":["b3c697b545bc47e2af05df3e8474d69e"],
                                  "moveInfo":{
                                    "moveType":"dragY",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "options":{
}}}]}]}]},
                    "onDragDrop":{
                      "description":"OnDragDrop",
                      "cases":[{
                          "description":"用例 1<br> (If area of 详情页 未接触 area of 固定点)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"fcall",
                            "functionName":"IsNotOver",
                            "arguments":[{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["b3c697b545bc47e2af05df3e8474d69e"]}]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["faad106095a645b8b1e5ad0acd9c4dca"]}]}]},
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 详情页 到 (0,67)",
                              "objectsToMoves":[{
                                  "objectPath":["b3c697b545bc47e2af05df3e8474d69e"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"67",
                                      "stos":[]},
                                    "options":{
}}}]}]},
{
                          "description":"用例 2<br> (Else If area of 详情页 未接触 area of 底部范围)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"fcall",
                            "functionName":"IsNotOver",
                            "arguments":[{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["b3c697b545bc47e2af05df3e8474d69e"]}]},
{
                                "exprType":"fcall",
                                "functionName":"GetWidgetRectangles",
                                "arguments":[{
                                    "exprType":"pathLiteral",
                                    "isThis":false,
                                    "isFocused":false,
                                    "isTarget":false,
                                    "value":["96aaab4670f74601b6b101dc27e7ca9b"]}]}]},
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 详情页 到 (0,-1255)",
                              "objectsToMoves":[{
                                  "objectPath":["b3c697b545bc47e2af05df3e8474d69e"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-1255",
                                      "stos":[]},
                                    "options":{
}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"347fab0104f64be4bbf489454a28207c",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"b3c697b545bc47e2af05df3e8474d69e",
                          "label":"详情页",
                          "parentDynamicPanel":"ac765c0c9e2e4a969e47aa318e110047",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":70},
                            "size":{
                              "width":373,
                              "height":1923}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"db0b433bd48b4fa385c262aa86e27d2e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"ac765c0c9e2e4a969e47aa318e110047",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":70},
                                "size":{
                                  "width":373,
                                  "height":1923}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/详情页/详情页_u6.jpg"}}]}]},
{
                  "id":"22656005af7843939a19436d4be767e1",
                  "label":"",
                  "parentDynamicPanel":"7e6e4d5dd41c482597158bd0f813b4cf",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":1940},
                    "size":{
                      "width":110,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 咨询设计师",
                              "target":{
                                "targetType":"page",
                                "url":"咨询设计师.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"ba5c454b8e0b470f86e1599b21a7a2aa",
          "label":"固定点",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":115,
              "y":72},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":115,
          "fixedVertical":"top",
          "fixedMarginVertical":72,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e91039632fb843a792fc17546ae246e3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2b08c546a8b3438badbb3b8430f6f260",
                  "label":"",
                  "parentDynamicPanel":"ba5c454b8e0b470f86e1599b21a7a2aa",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f6e09c4151c64582b64062d8c0c8de6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ba5c454b8e0b470f86e1599b21a7a2aa",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/详情页/u10.png"}}]}]},
{
          "id":"faad106095a645b8b1e5ad0acd9c4dca",
          "label":"固定点",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":374,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a41ad3dc0f0149b8ac93f50710b87fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":374,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页/固定点_u12.png"}},
{
          "id":"98418552416b41ffa3e36dad9ad9399c",
          "label":"返回",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":136},
            "size":{
              "width":40,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-方案",
                      "target":{
                        "targetType":"page",
                        "url":"首页-方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b2894bdb55c64db3ac66fa0d4f1abef3",
          "label":"分享",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":139},
            "size":{
              "width":25,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 第三方图标,<br>阴影",
                      "objectsToFades":[{
                          "objectPath":["62b5435c33b34bf0b4100c21eb245db2"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["5cc5b7e34bf241a4a7176cc8bca10f7a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"456c9b5ecba649c19c0dac3a9bc43ecf",
          "label":"收藏",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":135},
            "size":{
              "width":28,
              "height":27}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 收藏成功",
                      "objectsToFades":[{
                          "objectPath":["90bbfcb5c2684d389d79fcd5f396de29"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"90bbfcb5c2684d389d79fcd5f396de29",
          "label":"收藏成功",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":329,
              "y":139},
            "size":{
              "width":21,
              "height":21},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36958d09325a47cf88101cbdc3c38dc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":329,
                  "y":139},
                "size":{
                  "width":21,
                  "height":21},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 收藏成功",
                      "objectsToFades":[{
                          "objectPath":["90bbfcb5c2684d389d79fcd5f396de29"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/详情页/收藏成功_u17.png"}},
{
          "id":"5cc5b7e34bf241a4a7176cc8bca10f7a",
          "label":"阴影",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F666666},
            "location":{
              "x":28,
              "y":107},
            "size":{
              "width":375,
              "height":666},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"232858e18a284850869be3735d9911b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F666666},
                "location":{
                  "x":28,
                  "y":107},
                "size":{
                  "width":375,
                  "height":666},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 阴影,<br>第三方图标",
                      "objectsToFades":[{
                          "objectPath":["5cc5b7e34bf241a4a7176cc8bca10f7a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["62b5435c33b34bf0b4100c21eb245db2"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/详情页/阴影_u19.png"}},
{
          "id":"62b5435c33b34bf0b4100c21eb245db2",
          "label":"第三方图标",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":28,
              "y":652},
            "size":{
              "width":374,
              "height":121},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85b6f0d3398e4359852aaa72171866d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":28,
                  "y":652},
                "size":{
                  "width":374,
                  "height":121},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/详情页/第三方图标_u21.png"}},
{
          "id":"96aaab4670f74601b6b101dc27e7ca9b",
          "label":"底部范围",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":28,
              "y":773},
            "size":{
              "width":374,
              "height":17}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "b55d5f7044a847efa6fdedf20c95d455":{
      "scriptId":"u0"},
    "c2236d7959754c788c047725df208a23":{
      "scriptId":"u1"},
    "7e6e4d5dd41c482597158bd0f813b4cf":{
      "scriptId":"u2"},
    "1390fdffb5134c4c92b75debd0320915":{
      "scriptId":"u3"},
    "3587f35ebf5f4c7aa369bbc799d58a2a":{
      "scriptId":"u4"},
    "ac765c0c9e2e4a969e47aa318e110047":{
      "scriptId":"u5"},
    "b3c697b545bc47e2af05df3e8474d69e":{
      "scriptId":"u6"},
    "db0b433bd48b4fa385c262aa86e27d2e":{
      "scriptId":"u7"},
    "22656005af7843939a19436d4be767e1":{
      "scriptId":"u8"},
    "ba5c454b8e0b470f86e1599b21a7a2aa":{
      "scriptId":"u9"},
    "2b08c546a8b3438badbb3b8430f6f260":{
      "scriptId":"u10"},
    "f6e09c4151c64582b64062d8c0c8de6e":{
      "scriptId":"u11"},
    "faad106095a645b8b1e5ad0acd9c4dca":{
      "scriptId":"u12"},
    "a41ad3dc0f0149b8ac93f50710b87fbe":{
      "scriptId":"u13"},
    "98418552416b41ffa3e36dad9ad9399c":{
      "scriptId":"u14"},
    "b2894bdb55c64db3ac66fa0d4f1abef3":{
      "scriptId":"u15"},
    "456c9b5ecba649c19c0dac3a9bc43ecf":{
      "scriptId":"u16"},
    "90bbfcb5c2684d389d79fcd5f396de29":{
      "scriptId":"u17"},
    "36958d09325a47cf88101cbdc3c38dc0":{
      "scriptId":"u18"},
    "5cc5b7e34bf241a4a7176cc8bca10f7a":{
      "scriptId":"u19"},
    "232858e18a284850869be3735d9911b1":{
      "scriptId":"u20"},
    "62b5435c33b34bf0b4100c21eb245db2":{
      "scriptId":"u21"},
    "85b6f0d3398e4359852aaa72171866d4":{
      "scriptId":"u22"},
    "96aaab4670f74601b6b101dc27e7ca9b":{
      "scriptId":"u23"}}});