$axure.loadCurrentPage({
  "url":"我的设计.html",
  "generationDate":new Date(1488665387134.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"782e4f97970940918e4d36050c7fbddb",
    "type":"Axure:Page",
    "name":"我的设计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"41de2bdf47b343188f960c554cb6b977",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2855f2988b884d97a3885fa69d78d4bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的设计/u0.jpg"}},
{
          "id":"e9b9dc6dfabc422dac982539f73fae49",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":136},
            "size":{
              "width":230,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教程页",
                      "target":{
                        "targetType":"page",
                        "url":"教程页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"84791b62f48e41818d33e1d93f97fee1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":320},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d5e0bc90cc57470ea9552574965eb0cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":150},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b8bb275686e4a13a383b37e267a4220",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":150},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"598da5f6f1454af1b004345b1497cb27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":330},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87dd64c7e04d4a608cc1b0156f29d8d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":330},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"2b806b74be3d47d885aba8a1f70205d9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":669},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ddb9863abca4c85a8dcafc944155151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":669},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"1a9b3d6736df459b8805b539673d1ef2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1547.33325195313,
              "y":23},
            "size":{
              "width":50,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册登录",
                      "target":{
                        "targetType":"page",
                        "url":"注册登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"56ae0cef57094d57a85c9cc1fafce470",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1554,
              "y":23},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ecbd0ae17954817ac156f017eb703a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1554,
                  "y":23},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册登录",
                      "target":{
                        "targetType":"page",
                        "url":"注册登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"705cdac60dcd4abfb0025bd3ef2a2c10",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'苹方 中等', '苹方'",
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF459AE0,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD8D8D8},
            "location":{
              "x":305,
              "y":63},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4266ad67a2b49709ed664b1891bf88d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'苹方 中等', '苹方'",
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF459AE0,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD8D8D8},
                "location":{
                  "x":305,
                  "y":63},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的设计/u13.png"}},
{
          "id":"9bb3d1835a144c6b9edf364b5fb2df44",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":662},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 视频教程",
                      "target":{
                        "targetType":"page",
                        "url":"视频教程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "41de2bdf47b343188f960c554cb6b977":{
      "scriptId":"u0"},
    "2855f2988b884d97a3885fa69d78d4bf":{
      "scriptId":"u1"},
    "e9b9dc6dfabc422dac982539f73fae49":{
      "scriptId":"u2"},
    "84791b62f48e41818d33e1d93f97fee1":{
      "scriptId":"u3"},
    "d5e0bc90cc57470ea9552574965eb0cc":{
      "scriptId":"u4"},
    "2b8bb275686e4a13a383b37e267a4220":{
      "scriptId":"u5"},
    "598da5f6f1454af1b004345b1497cb27":{
      "scriptId":"u6"},
    "87dd64c7e04d4a608cc1b0156f29d8d7":{
      "scriptId":"u7"},
    "2b806b74be3d47d885aba8a1f70205d9":{
      "scriptId":"u8"},
    "8ddb9863abca4c85a8dcafc944155151":{
      "scriptId":"u9"},
    "1a9b3d6736df459b8805b539673d1ef2":{
      "scriptId":"u10"},
    "56ae0cef57094d57a85c9cc1fafce470":{
      "scriptId":"u11"},
    "9ecbd0ae17954817ac156f017eb703a9":{
      "scriptId":"u12"},
    "705cdac60dcd4abfb0025bd3ef2a2c10":{
      "scriptId":"u13"},
    "d4266ad67a2b49709ed664b1891bf88d":{
      "scriptId":"u14"},
    "9bb3d1835a144c6b9edf364b5fb2df44":{
      "scriptId":"u15"}}});