$axure.loadCurrentPage({
  "url":"套餐配置.html",
  "generationDate":new Date(1488665387812.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e02807d2d8dc49ff921ec9b5608d3915",
    "type":"Axure:Page",
    "name":"套餐配置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"23b08b1611064c83a576157a13a308e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"358b3dd62ce74b9698a8865da0789b70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐配置/u0.png"}},
{
          "id":"e021f43fa1df483bb8a46c0c6033ff99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fde56ca0c2f24105bd236efceebc2378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u2.png"}},
{
          "id":"c5d200a34e3441619753a5a37749f39d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c83871290d845a08df99b1fff01cc13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u4.png"}},
{
          "id":"c91d2c3254ff4fca8e249c6089709194",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":54},
            "size":{
              "width":123,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bcd1abc82b74b99b228531eeb4574d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1464,
                  "y":54},
                "size":{
                  "width":123,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u6.png"}},
{
          "id":"1ee4d47d07854238b19ff028558ea23d",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":182},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 素材库",
                      "target":{
                        "targetType":"page",
                        "url":"素材库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0c34623dedc94a72920ad3ca1ff14c7e",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":458,
              "y":284},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收藏",
                      "target":{
                        "targetType":"page",
                        "url":"收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"48b6128a4499485f9775082d036f0e5a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":530},
            "size":{
              "width":50,
              "height":46}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐方案",
                      "target":{
                        "targetType":"page",
                        "url":"套餐方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3c4d27165b144547b25319ccc83558f0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"65f701a3148b44efb74af645a4dbb1bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":801}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b683ee7ef556484892b0c8878b82eb61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":801}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐配置/u12.png"}},
{
          "id":"24d935a6f6e04f9ba9e52ac22f370be3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":56.5,
              "y":535},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a40fe7eed84d0a816555fb863e341a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56.5,
                  "y":535},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 套餐方案",
                      "target":{
                        "targetType":"page",
                        "url":"套餐方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"71540dacfa3b484090a63bbe6fe24555",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":314},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 https://www.rayion.com/RayPano_hc/",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.rayion.com/RayPano_hc/",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7b3eadfddd6a4162927603c3b78f5990",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":322},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aba3592a9976463a8ac6d4c3ba3f66f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":322},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 https://www.rayion.com/RayPano_hc/",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.rayion.com/RayPano_hc/",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"cc9217b8394f4b79982e66162f5641a2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":794},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 https://www.rayion.com/Raypano_ou/",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.rayion.com/Raypano_ou/",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e5e55500d5c644b39ff6d6d646393b55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":799},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db16ad17330e41faa1b165680887c05e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":799},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 https://www.rayion.com/Raypano_ou/",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"https://www.rayion.com/Raypano_ou/",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"7a2090b116f546f4be25b1a8d103b73e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bd09c0cd8b64cfea412baa710da35ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"05cbae54e902492186262fb988654cc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":186},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"999b385d4d464138a2567ce84599405a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":186},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 素材库",
                      "target":{
                        "targetType":"page",
                        "url":"素材库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"9f0abef32b6948c5b710b7d47fa2add2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":462,
              "y":286},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3328df8ab32549e08fde4c9ce9ce8c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":462,
                  "y":286},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收藏",
                      "target":{
                        "targetType":"page",
                        "url":"收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"245971d5b0cb4c22b166e7e9e1c39c06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":802}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46abc300b4554ffa98e1f39b0bc459f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":802}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u23.png"}},
{
          "id":"b4ef4c5bc0984ae5afebd93517ed820c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1464,
              "y":47},
            "size":{
              "width":66,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c008b07b56594e68a6efd2907391f18b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1470,
              "y":59},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe7c84181ef47e29a276f5de4e19d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1470,
                  "y":59},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 蓝图原型-创建户型",
                      "target":{
                        "targetType":"page",
                        "url":"蓝图原型-创建户型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"9098998b78c14dabb3f98bb11745537a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":98},
            "size":{
              "width":268,
              "height":802}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82ff9cd2ec514381b160f7a2fb635cd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":98},
                "size":{
                  "width":268,
                  "height":802}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u23.png"}},
{
          "id":"62ea947493e54c4aa60ac129aec4dd55",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":20},
            "size":{
              "width":59,
              "height":18}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"016c1c4f5d8c43c3b48578269e8e4eb8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":18},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52956145cf694091b1791f4da97c81a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":305,
                  "y":18},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"172e98f646134e71ad73a6844160cd6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":148.5,
              "y":42},
            "size":{
              "width":360,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51a2de18ee504489a53a7b5f1a08e35a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":148.5,
                  "y":42},
                "size":{
                  "width":360,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u28.png"}},
{
          "id":"110e72722e684b208697a4a4d19965e6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":750},
            "size":{
              "width":640,
              "height":130}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"26324b29998e41eaa5c59c9e5c16ffda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":820},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86aeb4ed6f2641a8b0075e74608027b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":820},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 地砖拼铺页面",
                      "target":{
                        "targetType":"page",
                        "url":"地砖拼铺页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"bb7b4a83d48c4b028d8632d48be52aad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF4B5161},
            "location":{
              "x":2,
              "y":136},
            "size":{
              "width":46,
              "height":92},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"301170c954104b4ea5782b0f13981d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4B5161},
                "location":{
                  "x":2,
                  "y":136},
                "size":{
                  "width":46,
                  "height":92},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u33.png"}},
{
          "id":"2a232be8b5b247a880dfc254e5460f27",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":196.5},
            "size":{
              "width":37,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d10ca920284d719db3febbea080f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":196.5},
                "size":{
                  "width":37,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de5d72e03d4b48c29ce6581fb4b2c6e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":147},
            "size":{
              "width":37,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53449559eef847b6bdedd02b8b3e8f09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":147},
                "size":{
                  "width":37,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb1d367497b14bf78aba1398f4610f8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cee15e6073f64ea9ba8ffef8569847b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1088,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u39.png"}},
{
          "id":"dbcc467e93714e168c5439f91af7810b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a449d26b0a8e4a2aaed754f76d9c930d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u41.png"}},
{
          "id":"a062c333f0134f1fa5364290e5419cc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1011,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f9667e69c024856a4e5c32a9c5ea57d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1011,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u43.png"}},
{
          "id":"270fede320aa43768f6c87dcb89bf6b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1240,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24763a75a9b147fab848ff0cafc618bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1240,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u45.png"}},
{
          "id":"31490035c14d4a9aa80f663bb08b2bec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":120},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5034f49a836945d38e1a26a9debd983c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":120},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/套餐方案/u47.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "23b08b1611064c83a576157a13a308e7":{
      "scriptId":"u0"},
    "358b3dd62ce74b9698a8865da0789b70":{
      "scriptId":"u1"},
    "e021f43fa1df483bb8a46c0c6033ff99":{
      "scriptId":"u2"},
    "fde56ca0c2f24105bd236efceebc2378":{
      "scriptId":"u3"},
    "c5d200a34e3441619753a5a37749f39d":{
      "scriptId":"u4"},
    "6c83871290d845a08df99b1fff01cc13":{
      "scriptId":"u5"},
    "c91d2c3254ff4fca8e249c6089709194":{
      "scriptId":"u6"},
    "9bcd1abc82b74b99b228531eeb4574d0":{
      "scriptId":"u7"},
    "1ee4d47d07854238b19ff028558ea23d":{
      "scriptId":"u8"},
    "0c34623dedc94a72920ad3ca1ff14c7e":{
      "scriptId":"u9"},
    "48b6128a4499485f9775082d036f0e5a":{
      "scriptId":"u10"},
    "3c4d27165b144547b25319ccc83558f0":{
      "scriptId":"u11"},
    "65f701a3148b44efb74af645a4dbb1bb":{
      "scriptId":"u12"},
    "b683ee7ef556484892b0c8878b82eb61":{
      "scriptId":"u13"},
    "24d935a6f6e04f9ba9e52ac22f370be3":{
      "scriptId":"u14"},
    "38a40fe7eed84d0a816555fb863e341a":{
      "scriptId":"u15"},
    "71540dacfa3b484090a63bbe6fe24555":{
      "scriptId":"u16"},
    "7b3eadfddd6a4162927603c3b78f5990":{
      "scriptId":"u17"},
    "aba3592a9976463a8ac6d4c3ba3f66f1":{
      "scriptId":"u18"},
    "cc9217b8394f4b79982e66162f5641a2":{
      "scriptId":"u19"},
    "e5e55500d5c644b39ff6d6d646393b55":{
      "scriptId":"u20"},
    "db16ad17330e41faa1b165680887c05e":{
      "scriptId":"u21"},
    "7a2090b116f546f4be25b1a8d103b73e":{
      "scriptId":"u22"},
    "0bd09c0cd8b64cfea412baa710da35ca":{
      "scriptId":"u23"},
    "05cbae54e902492186262fb988654cc5":{
      "scriptId":"u24"},
    "999b385d4d464138a2567ce84599405a":{
      "scriptId":"u25"},
    "9f0abef32b6948c5b710b7d47fa2add2":{
      "scriptId":"u26"},
    "3328df8ab32549e08fde4c9ce9ce8c1d":{
      "scriptId":"u27"},
    "245971d5b0cb4c22b166e7e9e1c39c06":{
      "scriptId":"u28"},
    "46abc300b4554ffa98e1f39b0bc459f2":{
      "scriptId":"u29"},
    "b4ef4c5bc0984ae5afebd93517ed820c":{
      "scriptId":"u30"},
    "c008b07b56594e68a6efd2907391f18b":{
      "scriptId":"u31"},
    "6fe7c84181ef47e29a276f5de4e19d5d":{
      "scriptId":"u32"},
    "9098998b78c14dabb3f98bb11745537a":{
      "scriptId":"u33"},
    "82ff9cd2ec514381b160f7a2fb635cd7":{
      "scriptId":"u34"},
    "62ea947493e54c4aa60ac129aec4dd55":{
      "scriptId":"u35"},
    "016c1c4f5d8c43c3b48578269e8e4eb8":{
      "scriptId":"u36"},
    "52956145cf694091b1791f4da97c81a6":{
      "scriptId":"u37"},
    "172e98f646134e71ad73a6844160cd6f":{
      "scriptId":"u38"},
    "51a2de18ee504489a53a7b5f1a08e35a":{
      "scriptId":"u39"},
    "110e72722e684b208697a4a4d19965e6":{
      "scriptId":"u40"},
    "26324b29998e41eaa5c59c9e5c16ffda":{
      "scriptId":"u41"},
    "86aeb4ed6f2641a8b0075e74608027b0":{
      "scriptId":"u42"},
    "bb7b4a83d48c4b028d8632d48be52aad":{
      "scriptId":"u43"},
    "301170c954104b4ea5782b0f13981d75":{
      "scriptId":"u44"},
    "2a232be8b5b247a880dfc254e5460f27":{
      "scriptId":"u45"},
    "c2d10ca920284d719db3febbea080f81":{
      "scriptId":"u46"},
    "de5d72e03d4b48c29ce6581fb4b2c6e4":{
      "scriptId":"u47"},
    "53449559eef847b6bdedd02b8b3e8f09":{
      "scriptId":"u48"},
    "fb1d367497b14bf78aba1398f4610f8f":{
      "scriptId":"u49"},
    "cee15e6073f64ea9ba8ffef8569847b5":{
      "scriptId":"u50"},
    "dbcc467e93714e168c5439f91af7810b":{
      "scriptId":"u51"},
    "a449d26b0a8e4a2aaed754f76d9c930d":{
      "scriptId":"u52"},
    "a062c333f0134f1fa5364290e5419cc7":{
      "scriptId":"u53"},
    "0f9667e69c024856a4e5c32a9c5ea57d":{
      "scriptId":"u54"},
    "270fede320aa43768f6c87dcb89bf6b6":{
      "scriptId":"u55"},
    "24763a75a9b147fab848ff0cafc618bf":{
      "scriptId":"u56"},
    "31490035c14d4a9aa80f663bb08b2bec":{
      "scriptId":"u57"},
    "5034f49a836945d38e1a26a9debd983c":{
      "scriptId":"u58"}}});