$axure.loadCurrentPage({
  "url":"设计平台-户型库.html",
  "generationDate":new Date(1488665387069.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"daa8d9b8709e4e88b2c023727fdd7a4c",
    "type":"Axure:Page",
    "name":"设计平台-户型库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a83718590eee43cb9e6842ee2b550077",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1600,
              "height":900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1bec1ae97144f0b8c0763216da4436c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1600,
                  "height":900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u0.jpg"}},
{
          "id":"6dcdb5ac67ad465baecee3ebcf99a395",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":136},
            "size":{
              "width":230,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教程页",
                      "target":{
                        "targetType":"page",
                        "url":"教程页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eb7ecd3ae67845e78df8f2aabe441138",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":433},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"f79d3f81286941549f2a8e8a186869ca",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":50},
            "size":{
              "width":70,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8693b5275288441286cd130d8df3d6c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":56.5},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e599e2e1bace4d5d8f1ba5b27a19a773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":56.5},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设计平台",
                      "target":{
                        "targetType":"page",
                        "url":"设计平台.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"ef78b74680ea449fa85f8a4d70962c2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":440},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9c18524b18346c9a52aed47cad92198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":440},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"e2e489e316d94494a3cc7a59f24d0506",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":150},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"723a11d4e48042b98e0c0261d2b9dad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":150},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"61ea1ec055714a0caf9bd1f89ceb4e54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":204},
            "size":{
              "width":294,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a010ee95c4c4e7aaae8ddf3a289f9a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":204},
                "size":{
                  "width":294,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u11.png"}},
{
          "id":"a1f397ad64c849dfb2dc2a94f6a6cdde",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":204},
            "size":{
              "width":294,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1398ec2526c44dfd8afcbcb740ac673b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":637,
                  "y":204},
                "size":{
                  "width":294,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u13.png"}},
{
          "id":"a5bc18a1f663481caaa8ad239ac166be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":949,
              "y":204},
            "size":{
              "width":295,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd761899ba664e4695670780f4849364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":949,
                  "y":204},
                "size":{
                  "width":295,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u15.png"}},
{
          "id":"af42918c20bc4a819cefee1c8d41cd21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1259,
              "y":204},
            "size":{
              "width":295,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b83e1c6b4c3e42b9806e844184b58e07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1259,
                  "y":204},
                "size":{
                  "width":295,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u17.png"}},
{
          "id":"6232f6bd131248f3949a5c0e193e635f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":492},
            "size":{
              "width":294,
              "height":208}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c121b3c1d6048f2b973e152e1b09f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":492},
                "size":{
                  "width":294,
                  "height":208}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u19.png"}},
{
          "id":"48285c161a4e49ac96d10b5bd1a6d45e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":492},
            "size":{
              "width":294,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94f9dedb5b54a459772bdfeb7bcc811",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":637,
                  "y":492},
                "size":{
                  "width":294,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u21.png"}},
{
          "id":"47c65bfdc4684923abc01f909c449b22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":949,
              "y":492},
            "size":{
              "width":295,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d9929ae2cf49df8cf1b31ec82d6b6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":949,
                  "y":492},
                "size":{
                  "width":295,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u23.png"}},
{
          "id":"2e2199e275ee42a78d97d7e9e9272c96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1259,
              "y":492},
            "size":{
              "width":295,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ede345783f435fbc95ecf8343baa2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1259,
                  "y":492},
                "size":{
                  "width":295,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u25.png"}},
{
          "id":"c879edb48eed4ae28a593acff6ac90e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":788},
            "size":{
              "width":294,
              "height":229}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2399d119d0184f58837f7f2b764ba783",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":788},
                "size":{
                  "width":294,
                  "height":229}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u13.png"}},
{
          "id":"b70067ece1e3494fac7e958c7e75e3ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":637,
              "y":788},
            "size":{
              "width":295,
              "height":229}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5721fb7fbac347e3ac7e5071a4a811e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":637,
                  "y":788},
                "size":{
                  "width":295,
                  "height":229}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u23.png"}},
{
          "id":"b2960eb4a3cd4bdea5205bc9cc5e2ce4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":949,
              "y":788},
            "size":{
              "width":294,
              "height":232}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf8c3b2e1f254c97bcdca1a37c93c694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":949,
                  "y":788},
                "size":{
                  "width":294,
                  "height":232}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u19.png"}},
{
          "id":"a69fa89b23b44fcca830f0c59bf59ac5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1259,
              "y":788},
            "size":{
              "width":295,
              "height":229}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f21425965fa4e939d3fa12e9dd03aa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1259,
                  "y":788},
                "size":{
                  "width":295,
                  "height":229}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u15.png"}},
{
          "id":"ca2971f88b0f49ecbb1bf17115c245c5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":662},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的设计",
                      "target":{
                        "targetType":"page",
                        "url":"我的设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"477ce1e941cb4aa596ea71fe1dd8dc35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":669},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4910f7f3931b42e5af647d40e3c8df75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":669},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"ee5b30c3325c42af81ab4ac342ba9e22",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1547.33325195313,
              "y":23},
            "size":{
              "width":50,
              "height":24}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册登录",
                      "target":{
                        "targetType":"page",
                        "url":"注册登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"bde8fe914c1240c7ae45e74e60b1e2c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1554,
              "y":23},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2fdf212283d4631a6cc252c752beb35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1554,
                  "y":23},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册登录",
                      "target":{
                        "targetType":"page",
                        "url":"注册登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/启动界面/u4.gif"}},
{
          "id":"fa5eb39897404985b671e3486749c1d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":900},
            "size":{
              "width":1420,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbdb27019460449088854d788111cefc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":900},
                "size":{
                  "width":1420,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计平台-户型库/u41.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a83718590eee43cb9e6842ee2b550077":{
      "scriptId":"u0"},
    "d1bec1ae97144f0b8c0763216da4436c":{
      "scriptId":"u1"},
    "6dcdb5ac67ad465baecee3ebcf99a395":{
      "scriptId":"u2"},
    "eb7ecd3ae67845e78df8f2aabe441138":{
      "scriptId":"u3"},
    "f79d3f81286941549f2a8e8a186869ca":{
      "scriptId":"u4"},
    "8693b5275288441286cd130d8df3d6c7":{
      "scriptId":"u5"},
    "e599e2e1bace4d5d8f1ba5b27a19a773":{
      "scriptId":"u6"},
    "ef78b74680ea449fa85f8a4d70962c2f":{
      "scriptId":"u7"},
    "c9c18524b18346c9a52aed47cad92198":{
      "scriptId":"u8"},
    "e2e489e316d94494a3cc7a59f24d0506":{
      "scriptId":"u9"},
    "723a11d4e48042b98e0c0261d2b9dad2":{
      "scriptId":"u10"},
    "61ea1ec055714a0caf9bd1f89ceb4e54":{
      "scriptId":"u11"},
    "6a010ee95c4c4e7aaae8ddf3a289f9a1":{
      "scriptId":"u12"},
    "a1f397ad64c849dfb2dc2a94f6a6cdde":{
      "scriptId":"u13"},
    "1398ec2526c44dfd8afcbcb740ac673b":{
      "scriptId":"u14"},
    "a5bc18a1f663481caaa8ad239ac166be":{
      "scriptId":"u15"},
    "bd761899ba664e4695670780f4849364":{
      "scriptId":"u16"},
    "af42918c20bc4a819cefee1c8d41cd21":{
      "scriptId":"u17"},
    "b83e1c6b4c3e42b9806e844184b58e07":{
      "scriptId":"u18"},
    "6232f6bd131248f3949a5c0e193e635f":{
      "scriptId":"u19"},
    "8c121b3c1d6048f2b973e152e1b09f56":{
      "scriptId":"u20"},
    "48285c161a4e49ac96d10b5bd1a6d45e":{
      "scriptId":"u21"},
    "f94f9dedb5b54a459772bdfeb7bcc811":{
      "scriptId":"u22"},
    "47c65bfdc4684923abc01f909c449b22":{
      "scriptId":"u23"},
    "00d9929ae2cf49df8cf1b31ec82d6b6d":{
      "scriptId":"u24"},
    "2e2199e275ee42a78d97d7e9e9272c96":{
      "scriptId":"u25"},
    "07ede345783f435fbc95ecf8343baa2a":{
      "scriptId":"u26"},
    "c879edb48eed4ae28a593acff6ac90e6":{
      "scriptId":"u27"},
    "2399d119d0184f58837f7f2b764ba783":{
      "scriptId":"u28"},
    "b70067ece1e3494fac7e958c7e75e3ca":{
      "scriptId":"u29"},
    "5721fb7fbac347e3ac7e5071a4a811e3":{
      "scriptId":"u30"},
    "b2960eb4a3cd4bdea5205bc9cc5e2ce4":{
      "scriptId":"u31"},
    "cf8c3b2e1f254c97bcdca1a37c93c694":{
      "scriptId":"u32"},
    "a69fa89b23b44fcca830f0c59bf59ac5":{
      "scriptId":"u33"},
    "0f21425965fa4e939d3fa12e9dd03aa0":{
      "scriptId":"u34"},
    "ca2971f88b0f49ecbb1bf17115c245c5":{
      "scriptId":"u35"},
    "477ce1e941cb4aa596ea71fe1dd8dc35":{
      "scriptId":"u36"},
    "4910f7f3931b42e5af647d40e3c8df75":{
      "scriptId":"u37"},
    "ee5b30c3325c42af81ab4ac342ba9e22":{
      "scriptId":"u38"},
    "bde8fe914c1240c7ae45e74e60b1e2c1":{
      "scriptId":"u39"},
    "d2fdf212283d4631a6cc252c752beb35":{
      "scriptId":"u40"},
    "fa5eb39897404985b671e3486749c1d9":{
      "scriptId":"u41"},
    "cbdb27019460449088854d788111cefc":{
      "scriptId":"u42"}}});