$axure.loadCurrentPage({
  "url":"擅长风格.html",
  "generationDate":new Date(1479704708782.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"eb51431e05a64f39ab8b35ef740d9eb7",
    "type":"Axure:Page",
    "name":"擅长风格",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4e25711688e745c8987aa12a86a69099",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aca376a607514b75aec35caee146667c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"ff88c5d0d25c4184acca30239d4fdf24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad1fb12847634210be6b6d5204103f4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/擅长风格/u2.jpg"}},
{
          "id":"25415c98424d4abb991827dab833919e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":727},
            "size":{
              "width":73,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1db1bef8ccf4f9f8122c8355bfcb3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":727},
                "size":{
                  "width":73,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/擅长风格/u4.png"}},
{
          "id":"d07e06cb57914812bbf4d56d52641ffd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":360},
            "size":{
              "width":373,
              "height":360}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 预约设计师",
                      "target":{
                        "targetType":"page",
                        "url":"预约设计师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"66920fa8e4914358999c2b7563a155d2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":726},
            "size":{
              "width":73,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-方案",
                      "target":{
                        "targetType":"page",
                        "url":"首页-方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"729db83c123d416999d4c33843fe74dd",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":727},
            "size":{
              "width":78,
              "height":49}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新家--案例",
                      "target":{
                        "targetType":"page",
                        "url":"新家--案例.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4b63fd9db8d943e8ba74abf8f2a39977",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":726},
            "size":{
              "width":60,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的",
                      "target":{
                        "targetType":"page",
                        "url":"我的.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4e25711688e745c8987aa12a86a69099":{
      "scriptId":"u0"},
    "aca376a607514b75aec35caee146667c":{
      "scriptId":"u1"},
    "ff88c5d0d25c4184acca30239d4fdf24":{
      "scriptId":"u2"},
    "ad1fb12847634210be6b6d5204103f4a":{
      "scriptId":"u3"},
    "25415c98424d4abb991827dab833919e":{
      "scriptId":"u4"},
    "e1db1bef8ccf4f9f8122c8355bfcb3da":{
      "scriptId":"u5"},
    "d07e06cb57914812bbf4d56d52641ffd":{
      "scriptId":"u6"},
    "66920fa8e4914358999c2b7563a155d2":{
      "scriptId":"u7"},
    "729db83c123d416999d4c33843fe74dd":{
      "scriptId":"u8"},
    "4b63fd9db8d943e8ba74abf8f2a39977":{
      "scriptId":"u9"}}});