$axure.loadCurrentPage({
  "url":"高级-立即预约.html",
  "generationDate":new Date(1479704709286.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ead40edd315c453699f19ca0032d17ac",
    "type":"Axure:Page",
    "name":"高级-立即预约",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0bf661e772e14448b69e23d14427c51e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a51692855ee94d8ca21cb6a2594bc910",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"17e4118f7d624ba1bfd336fc552ebeec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5ebed1f5c04d2587edad764dac397b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"d1989f562c6f44f69b4c8d956046fedc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbf2198a13114c45a2975d34ee0c547c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/立即预约-上门量房/u2.png"}},
{
          "id":"52a26812f9b04065bfedcd8559f13117",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":120},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 高级设计套餐",
                      "target":{
                        "targetType":"page",
                        "url":"高级设计套餐.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"07e64b672717452791a7ba8fb07311ab",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":130},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结算",
                      "target":{
                        "targetType":"page",
                        "url":"结算.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0bf661e772e14448b69e23d14427c51e":{
      "scriptId":"u0"},
    "a51692855ee94d8ca21cb6a2594bc910":{
      "scriptId":"u1"},
    "17e4118f7d624ba1bfd336fc552ebeec":{
      "scriptId":"u2"},
    "bc5ebed1f5c04d2587edad764dac397b":{
      "scriptId":"u3"},
    "d1989f562c6f44f69b4c8d956046fedc":{
      "scriptId":"u4"},
    "cbf2198a13114c45a2975d34ee0c547c":{
      "scriptId":"u5"},
    "52a26812f9b04065bfedcd8559f13117":{
      "scriptId":"u6"},
    "07e64b672717452791a7ba8fb07311ab":{
      "scriptId":"u7"}}});