$axure.loadCurrentPage({
  "url":"搜索.html",
  "generationDate":new Date(1479704708547.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a25e0b03bf8047d5834a7b60f9421949",
    "type":"Axure:Page",
    "name":"搜索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d885c5a0732f4f10a8bdbdd1ee07cdc7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":430,
              "height":880}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0667dc06094a4770bb0bd0355c78ca4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":430,
                  "height":880}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/app/u1.jpg"}},
{
          "id":"716a376cdca149a8b0d420dedc6667d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":108},
            "size":{
              "width":375,
              "height":668}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bc9e0841d1b421bb025bd2f873d541c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":108},
                "size":{
                  "width":375,
                  "height":668}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u2.png"}},
{
          "id":"27f39d3c68c04c6f8eca548daa0b54a6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":130},
            "size":{
              "width":40,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-方案",
                      "target":{
                        "targetType":"page",
                        "url":"首页-方案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"fde05cbf9f9c46078f9d18fcb09f47dc",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":230},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 详情页",
                      "target":{
                        "targetType":"page",
                        "url":"详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "d885c5a0732f4f10a8bdbdd1ee07cdc7":{
      "scriptId":"u0"},
    "0667dc06094a4770bb0bd0355c78ca4e":{
      "scriptId":"u1"},
    "716a376cdca149a8b0d420dedc6667d6":{
      "scriptId":"u2"},
    "1bc9e0841d1b421bb025bd2f873d541c":{
      "scriptId":"u3"},
    "27f39d3c68c04c6f8eca548daa0b54a6":{
      "scriptId":"u4"},
    "fde05cbf9f9c46078f9d18fcb09f47dc":{
      "scriptId":"u5"}}});